/**
 * Generates one SQL view per tender form, projecting the JSON answers in
 * TenderFormData.Data back into columns.
 *
 * Registering that view as a ModelConfig gives list, multi-field search, sort
 * and /BaseObject/ExportExcel from the existing generic controller, with no
 * per-form backend code. The view is generated rather than hand-written so it
 * can never drift from the field dictionary.
 *
 *   node scripts/generate_form_views.js            # write + apply all forms
 *   node scripts/generate_form_views.js 1.1        # one form
 *   node scripts/generate_form_views.js --print    # print SQL, apply nothing
 *
 * JSON_VALUE returns nvarchar(4000); numbers and dates are CAST so the grid
 * sorts and filters them correctly rather than as text.
 */
require('dotenv').config({ path: './config/Config.env' });

const fs = require('fs');
const path = require('path');
const { Models, sequelize } = require('../config/DB');

const OUT_DIR = path.join(__dirname, 'generated');

const viewName = (formCode) => 'vwForm_' + String(formCode).replace(/[^A-Za-z0-9]/g, '_');

function columnExpr(field) {
  const jsonPath = `'$.${field.FieldCode}'`;
  const raw = `JSON_VALUE(d.Data, ${jsonPath})`;
  switch (field.FieldType) {
    case 'Number':
      return `TRY_CAST(${raw} AS decimal(18,4))`;
    case 'Date':
      return `TRY_CAST(${raw} AS date)`;
    case 'DateTime':
      return `TRY_CAST(${raw} AS datetime)`;
    default:
      return `CAST(${raw} AS nvarchar(4000))`;
  }
}

function buildViewSql(formCode, fields) {
  const name = viewName(formCode);
  const cols = fields.map((f) => `       ${columnExpr(f)} AS [${f.FieldCode}]`);

  return `-- GENERATED by scripts/generate_form_views.js - do not edit by hand.
-- Form ${formCode}: ${fields.length} field columns projected from TenderFormData.Data
CREATE OR ALTER VIEW dbo.${name} AS
SELECT d.Id,
       d.FormCode,
       d.PatRegNo,
       d.PatientId,
       d.FormDate,
       d.DoctorId,
       d.OrganizationId,
       d.Status,
       d.rec_status,
       d.CreateDate,
       d.CreateUserId,
       d.UpdateDate,
${cols.join(',\n')}
FROM dbo.TenderFormData d
WHERE d.FormCode = '${formCode}'
  AND ISNULL(d.rec_status, 1) <> 2;
`;
}

/** the Sequelize model file that maps onto the view */
function buildModelJs(formCode, fields) {
  const name = viewName(formCode);
  const typeOf = (f) =>
    f.FieldType === 'Number'
      ? 'Sequelize.DECIMAL'
      : f.FieldType === 'Date'
        ? 'Sequelize.DATEONLY'
        : f.FieldType === 'DateTime'
          ? 'Sequelize.DATE'
          : 'Sequelize.STRING';

  const base = [
    ['Id', 'Sequelize.INTEGER', true],
    ['FormCode', 'Sequelize.STRING'],
    ['PatRegNo', 'Sequelize.STRING'],
    ['PatientId', 'Sequelize.INTEGER'],
    ['FormDate', 'Sequelize.DATEONLY'],
    ['DoctorId', 'Sequelize.INTEGER'],
    ['OrganizationId', 'Sequelize.INTEGER'],
    ['Status', 'Sequelize.INTEGER'],
    ['rec_status', 'Sequelize.INTEGER'],
    ['CreateDate', 'Sequelize.DATE'],
    ['CreateUserId', 'Sequelize.INTEGER'],
    ['UpdateDate', 'Sequelize.DATE'],
  ];

  const attrLines = base
    .map(([n, t, pk]) => `    ${n}: { type: ${t}${pk ? ', primaryKey: true' : ''} },`)
    .concat(fields.map((f) => `    ${f.FieldCode}: { type: ${typeOf(f)} },`))
    .join('\n');

  const searchFields = base
    .map(([n]) => n)
    .concat(fields.map((f) => f.FieldCode))
    .map((n) => `'${n}'`)
    .join(', ');

  return `// GENERATED by scripts/generate_form_views.js - do not edit by hand.
const Sequelize = require('sequelize');
const sequelize = require('../../config/DbConnection');

class ${name} extends Sequelize.Model {}
${name}.init(
  {
${attrLines}
  },
  { sequelize, tableName: '${name}', modelName: '${name}', timestamps: false }
);

${name}.SearchField = [${searchFields}];

module.exports = ${name};
`;
}

/**
 * Emits one module holding a ModelConfig for every form view, so the generic
 * /BaseObject controller can list, search, sort and Excel-export them.
 * mainConfig.js spreads this in, which means adding a new form stays a matter
 * of dictionary rows plus a re-run of this script - no hand-edited config.
 */
function buildConfigsJs(all) {
  const entries = all
    .map(({ form, fields }) => {
      const name = viewName(form.FormCode);
      const cols = [
        `        { Name: 'Id', Label: 'Id', Type: 'Text', GridField: false },`,
        `        { Name: 'PatRegNo', Label: 'Регистрийн дугаар', Type: 'Text', Position: 1, md: 3 },`,
        `        { Name: 'FormDate', Label: 'Огноо', Type: 'Date', Position: 2, md: 3 },`,
        `        { Name: 'Status', Label: 'Төлөв', Type: 'Text', Position: 3, md: 2 },`,
      ].concat(
        fields.map(
          (f, i) =>
            `        { Name: '${f.FieldCode}', Label: ${JSON.stringify(f.LabelMn)}, Type: 'Text', Position: ${10 + i}, md: 4 },`
        )
      );

      return `  {
    ObjectName: '${name}',
    Model: Models.${name},
    PK: 'Id',
    NewObject: {},
    TitleObject: {
      Title: ${JSON.stringify(form.NameMn)},
      NewObjectTitle: ${JSON.stringify(form.NameMn)},
      EditObjectTitle: ${JSON.stringify(form.NameMn)},
    },
    Fields: [
      [
${cols.join('\n')}
      ],
    ],
  },`;
    })
    .join('\n');

  return `// GENERATED by scripts/generate_form_views.js - do not edit by hand.
// One ModelConfig per tender-form view, so /BaseObject gives list, search,
// sort and Excel export for each form with no per-form code.
const { Models } = require('../../config/DB');

module.exports = function FormViewConfigs() {
  return [
${entries}
  ];
};
`;
}

(async () => {
  const only = process.argv.slice(2).filter((a) => !a.startsWith('--'))[0] || null;
  const printOnly = process.argv.includes('--print');
  const generated = [];

  const where = { IsActive: true };
  if (only) where.FormCode = only;

  const forms = await Models.TenderForm.findAll({
    where: only ? { FormCode: only } : {},
    order: [['Position', 'ASC']],
    raw: true,
  });

  if (forms.length === 0) {
    console.log('no forms found' + (only ? ' for ' + only : ''));
    process.exit(1);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const modelDir = path.join(__dirname, '..', 'model', 'views');

  for (const form of forms) {
    const fields = await Models.TenderFormField.findAll({
      where: { FormCode: form.FormCode, IsActive: true },
      order: [
        ['SectionPos', 'ASC'],
        ['Position', 'ASC'],
      ],
      raw: true,
    });

    // a repeating Table field holds a JSON array, not a scalar - it cannot be
    // projected into a view column, so it is left out of the view and the grid
    const scalar = fields.filter((f) => f.FieldType !== 'Table');

    if (fields.length === 0) {
      console.log(`${form.FormCode.padEnd(5)} no fields defined - skipped`);
      continue;
    }

    const sql = buildViewSql(form.FormCode, scalar);
    const name = viewName(form.FormCode);

    const sqlPath = path.join(OUT_DIR, name + '.sql');
    fs.writeFileSync(sqlPath, sql, 'utf8');

    const modelPath = path.join(modelDir, name + '.js');
    fs.writeFileSync(modelPath, buildModelJs(form.FormCode, scalar), 'utf8');

    if (printOnly) {
      console.log(sql);
      continue;
    }

    generated.push({ form, fields: scalar });
    await sequelize.query(sql);
    const [[check]] = await sequelize.query(
      `SELECT COUNT(*) AS c FROM sys.views WHERE name = '${name}'`
    );
    console.log(
      `${form.FormCode.padEnd(5)} ${name.padEnd(16)} ${String(fields.length).padStart(3)} fields  ` +
        `view=${check.c ? 'ok' : 'MISSING'}  model=${path.basename(modelPath)}`
    );
  }

  if (!printOnly && generated.length) {
    // FormViewConfigs.js holds EVERY form, so it can only be written from a
    // full run. Rewriting it after `node generate_form_views.js 1.2` would
    // silently drop the other ten forms' configs and take their whole list
    // screen with them - which is exactly what happened once.
    if (only) {
      console.log(
        '\nView and model written for ' +
          only +
          ', but ModelConfigs/View/FormViewConfigs.js was NOT rewritten:\n' +
          'it contains every form and can only be regenerated from a full run.\n' +
          'Run `node scripts/generate_form_views.js` with no argument to refresh it.'
      );
    } else {
      const cfgDir = path.join(__dirname, '..', 'ModelConfigs', 'View');
      fs.mkdirSync(cfgDir, { recursive: true });
      const cfgPath = path.join(cfgDir, 'FormViewConfigs.js');
      fs.writeFileSync(cfgPath, buildConfigsJs(generated), 'utf8');
      console.log(
        'wrote ModelConfigs/View/FormViewConfigs.js (' + generated.length + ' form config(s))'
      );
    }
  }

  console.log('\nSQL written to', OUT_DIR);
  process.exit(0);
})().catch((e) => {
  console.error('FAILED:', e.message);
  process.exit(1);
});
