-- =============================================================================
-- Form 2.2  ТОСГУУРЫН ЖИГВЭГНЭЭ БҮРТГЭЛ СУДАЛГАА
-- Source: "MN cardio upgrade.docx", appendix 2.2
-- GENERATED from the document's checkbox structure.
--
-- 244 fields in 92 sections, 91 option sets.
-- Labels and option text are verbatim from the tender. Field codes and types
-- are derived and NOT approved - clinical sign-off is the customer's step.
--
-- The existing AtrialRhythmNew screen is untouched and keeps serving its data.
-- Run seed_optiontypes_2_2.sql FIRST.
-- =============================================================================
SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @db sysname = DB_NAME();
IF @db NOT IN ('MnCardio_restored','MnCardioNew','MnCardio_test')
BEGIN RAISERROR('Refusing to run: unexpected database "%s".',16,1,@db); SET NOEXEC ON; END
GO

DECLARE @Form varchar(20) = '2.2';
BEGIN TRAN;

IF EXISTS (SELECT 1 FROM dbo.TenderForm WHERE FormCode=@Form)
    UPDATE dbo.TenderForm SET NameMn=N'Тосгуурын жигвэгнээ бүртгэл судалгаа',
        GroupCode='rhythm', GroupLabelMn=N'Зүрх судасны хэм судлалын маягтууд',
        Position=22, IsActive=1, UpdateDate=GETDATE() WHERE FormCode=@Form;
ELSE
    INSERT INTO dbo.TenderForm (FormCode,NameMn,GroupCode,GroupLabelMn,Position)
    VALUES (@Form,N'Тосгуурын жигвэгнээ бүртгэл судалгаа','rhythm',N'Зүрх судасны хэм судлалын маягтууд',22);

DELETE FROM dbo.TenderFormField WHERE FormCode=@Form;

INSERT INTO dbo.TenderFormField
 (FormCode,FieldCode,LabelMn,FieldType,OptionType,SectionCode,SectionLabel,SectionPos,
  ParentField,ParentValue,IsRequired,IsSearchable,Md,Position,HelpTextMn)
VALUES
(@Form,'VzlegiinOgnooEmnelegtHevtsenOgnooUdur',N'Үзлэгийн огноо / Эмнэлэгт хэвтсэн огноо|_ _/_ _/_ _ _ _| өдөр сар он','Date',NULL,'s1',N'Үзлэг № 1 - Эхний үзлэг',1,NULL,NULL,0,0,12,10,NULL),
(@Form,'EmchlvvlegchiinTurul',N'Эмчлүүлэгчийн төрөл:','RadioBox','f22_01','s2',N'Хэвтэн эмчлүүлэх/Зөвлөгөөний мэдээлэл',2,NULL,NULL,0,0,12,20,NULL),
(@Form,'HevtenEmchlvvlehZuvluguuAvahTurul',N'Хэвтэн эмчлүүлэх/зөвлөгөө авах төрөл:','RadioBox','f22_03','s2',N'Хэвтэн эмчлүүлэх/Зөвлөгөөний мэдээлэл',2,NULL,NULL,0,0,12,30,NULL),
(@Form,'TusEmchlvvlegchiigHenYavuulsanBe',N'Тус эмчлүүлэгчийг хэн явуулсан бэ?','RadioBox','f22_06','s2',N'Хэвтэн эмчлүүлэх/Зөвлөгөөний мэдээлэл',2,NULL,NULL,0,0,12,40,NULL),
(@Form,'TuslamjVilchilgeeniiHamrahNegj',N'Тусламж үйлчилгээний хамрах нэгж:','RadioBox','f22_12','s2',N'Хэвтэн эмчлүүлэх/Зөвлөгөөний мэдээлэл',2,NULL,NULL,0,0,12,50,NULL),
(@Form,'Hvis',N'Хүйс:','RadioBox','f22_13','s3',N'Оролцогчийн мэдээлэл',3,NULL,NULL,0,0,12,60,NULL),
(@Form,'EmegteiBolTsevershsenVv',N'Эмэгтэй бол цэвэршсэн үү?:','RadioBox','f22_14','s3',N'Оролцогчийн мэдээлэл',3,NULL,NULL,0,0,12,70,NULL),
(@Form,'EmchlvvlegchiinTursunOgnooSarJil',N'Эмчлүүлэгчийн төрсөн огноо:|_ _ / _ _ _ _| сар/жил','Date',NULL,'s3',N'Оролцогчийн мэдээлэл',3,NULL,NULL,0,0,12,80,NULL),
(@Form,'AmdralynOrchin',N'Амьдралын орчин:','RadioBox','f22_15','s3',N'Оролцогчийн мэдээлэл',3,NULL,NULL,0,0,12,90,NULL),
(@Form,'GerBvliinBaidal',N'Гэр бүлийн байдал:','RadioBox','f22_16','s3',N'Оролцогчийн мэдээлэл',3,NULL,NULL,0,0,12,100,NULL),
(@Form,'ShinjTemdegEhelsenOgnooUdurSar',N'Шинж тэмдэг эхэлсэн огноо|__/__/ | өдөр/сар/жил','RadioBox','f22_17','s4',N'Зүрх судасны өвчлөлийн талаарх мэдээлэл / асуумж',4,NULL,NULL,0,0,12,110,NULL),
(@Form,'EmnelegtAnhVzvvlsen',N'Эмнэлэгт анх үзүүлсэн (шинж тэмдэг эхэлсний дараа)','Text',NULL,'s4',N'Зүрх судасны өвчлөлийн талаарх мэдээлэл / асуумж',4,NULL,NULL,0,0,12,120,NULL),
(@Form,'OgnooUdurSarJil',N'Огноо: |__/__/ | өдөр/сар/жил','RadioBox','f22_17','s4',N'Зүрх судасны өвчлөлийн талаарх мэдээлэл / асуумж',4,NULL,NULL,0,0,12,130,NULL),
(@Form,'Haana',N'Хаана:','RadioBox','f22_21','s4',N'Зүрх судасны өвчлөлийн талаарх мэдээлэл / асуумж',4,NULL,NULL,0,0,12,140,NULL),
(@Form,'EmnelegtAnhHevtsenOgnooUdurSar',N'Эмнэлэгт анх хэвтсэн огноо (одоогийн өвчлөл): |__/__/ | өдөр/сар/жил','RadioBox','f22_17','s4',N'Зүрх судасны өвчлөлийн талаарх мэдээлэл / асуумж',4,NULL,NULL,0,0,12,150,NULL),
(@Form,'UrdchilsanOnoshTavigdsanUdurSarJil',N'Урьдчилсан онош тавигдсан:|__/__/ | өдөр/сар/жил','RadioBox','f22_17','s4',N'Зүрх судасны өвчлөлийн талаарх мэдээлэл / асуумж',4,NULL,NULL,0,0,12,160,NULL),
(@Form,'JinKg',N'Жин: кг','RadioBox','f22_17','s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,170,NULL),
(@Form,'UndurSm',N'Өндөр: см','RadioBox','f22_17','s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,180,NULL),
(@Form,'BieiinJingiinIndeksKgM',N'Биеийн жингийн индекс (БЖИ): (автомат тооцсон) кг/м²','Number',NULL,'s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,190,NULL),
(@Form,'BieiinGadarguugiinTalbaiM',N'Биеийн гадаргуугийн талбай (BSA): м² (автомат тооцсон)','Number',NULL,'s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,200,NULL),
(@Form,'SistolynDaraltMmMUB',N'Систолын даралт: ммМУБ','RadioBox','f22_17','s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,210,NULL),
(@Form,'DiastolynDaraltMmMUB',N'Диастолын даралт: ммМУБ','RadioBox','f22_17','s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,220,NULL),
(@Form,'ZvrhniiTsohiltynTooUdaaMin',N'Зүрхний цохилтын тоо: удаа/мин','RadioBox','f22_17','s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,230,NULL),
(@Form,'SinusynHemneltei',N'Синусын хэмнэлтэй?:','RadioBox','f22_14','s5',N'Бодит үзлэг',5,NULL,NULL,0,0,12,240,NULL),
(@Form,'HerevTiimBol',N'Хэрэв тийм бол','Text',NULL,'s6',N'Цээжээр өвдөх',6,NULL,NULL,0,0,12,250,NULL),
(@Form,'ZTsBHiisenVv',N'ЗЦБ хийсэн үү?','RadioBox','f22_14','s11',N'Зүрхний цахилгаан бичлэг (ЗЦБ)',11,NULL,NULL,0,0,12,260,NULL),
(@Form,'TiimBolZTsBHiisenOgnoogOruulah',N'Тийм бол ЗЦБ хийсэн огноог оруулах:|_ _/_ _/_ _ _ _| өдөр сар жил','RadioBox','f22_17','s11',N'Зүрхний цахилгаан бичлэг (ЗЦБ)',11,NULL,NULL,0,0,12,270,NULL),
(@Form,'ZvrhniiHetAviaShinjilgeeHiisenEseh',N'Зүрхний хэт авиа шинжилгээ хийсэн эсэх','RadioBox','f22_14','s13',N'Зүрхний хэт авиан шинжилгээ (ЗХАШ)',13,NULL,NULL,0,0,12,280,NULL),
(@Form,'TiimBolShinjilgeeniiOgnoogBichneVv',N'Тийм бол шинжилгээний огноог бичнэ үү:|_ _/_ _/_ _ _ _| хоног/өдөр/он','RadioBox','f22_17','s13',N'Зүрхний хэт авиан шинжилгээ (ЗХАШ)',13,NULL,NULL,0,0,12,290,NULL),
(@Form,'TseejniiRentgenZuragAvsanEseh',N'Цээжний рентген зураг авсан эсэх,','RadioBox','f22_14','s16',N'Цээжний рентген зураг',16,NULL,NULL,0,0,12,300,NULL),
(@Form,'TiimBolShinjilgeeniiOgnoogBichneVv2',N'Тийм бол шинжилгээний огноог бичнэ үү:|_ _/_ _/_ _ _ _| хоног/өдөр/он','RadioBox','f22_17','s16',N'Цээжний рентген зураг',16,NULL,NULL,0,0,12,310,NULL),
(@Form,'CHADS2VAScOnooTootsoh',N'CHADS2-VASc оноо тооцох','Number',NULL,'s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,320,NULL),
(@Form,'CHADS2VAScOnooVnelsenEseh',N'CHADS2-VASc оноо үнэлсэн эсэх?','RadioBox','f22_14','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,330,NULL),
(@Form,'TiimBolTodruulnaUuCHADS2VASc',N'Тийм бол тодруулна уу -CHADS2-VASc оноо үнэлсэн огноо:|_ _/_ _/_ _ _ _| өдөр сар он','RadioBox','f22_17','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,340,NULL),
(@Form,'CHADS2VAScOnoo',N'CHADS2-VASc оноо*','Text',NULL,'s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,350,NULL),
(@Form,'Nas',N'Нас:','RadioBox','f22_22','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,360,NULL),
(@Form,'Hvis2',N'Хүйс:','RadioBox','f22_23','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,370,NULL),
(@Form,'ZvrhniiArhagDutagdal',N'Зүрхний архаг дутагдал:','RadioBox','f22_24','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,380,NULL),
(@Form,'ArteriinGipertenzi',N'Артерийн гипертензи:','RadioBox','f22_24','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,390,NULL),
(@Form,'TarhinyHarvaltTIA',N'Тархины харвалт/TIA/:','RadioBox','f22_25','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,400,NULL),
(@Form,'ZahynSudasnyEmgeg',N'Захын судасны эмгэг:','RadioBox','f22_24','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,410,NULL),
(@Form,'ChihriinShijin',N'Чихрийн шижин:','RadioBox','f22_24','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,420,NULL),
(@Form,'EHRAOnooTootsoh',N'EHRA оноо тооцох','Number',NULL,'s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,430,NULL),
(@Form,'EHRAOnooVnelsenVv',N'EHRA Оноо үнэлсэн үү?','RadioBox','f22_14','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,440,NULL),
(@Form,'TiimBolTodruulnaUuEHRAOnoo',N'Тийм бол тодруулна уу - EHRA оноо 2 үнэлсэн огноо:|_ _/_ _/_ _ _ _| өдөр сар он','RadioBox','f22_17','s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,450,NULL),
(@Form,'EHRAOnoo2GarsanUtga',N'EHRA оноо 2 гарсан утга*','Text',NULL,'s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,460,NULL),
(@Form,'EHRAOnoo',N'EHRA оноо','Text',NULL,'s18',N'Эмнэлзүйн үнэлгээний оноо',18,NULL,NULL,0,0,12,470,NULL),
(@Form,'HASBLEDErsdeliinVnelgeeHiisenVv',N'HAS-BLED Эрсдэлийн үнэлгээ хийсэн үү?','RadioBox','f22_14','s19',N'HAS-BLED Цус алдах эрсдэлийн үнэлгээ',19,NULL,NULL,0,0,12,480,NULL),
(@Form,'TiimBolTodruulnaUuOgnooUdur',N'Тийм бол тодруулна уу -Огноо :|_ _/_ _/_ _ _ _| өдөр сар он','RadioBox','f22_17','s19',N'HAS-BLED Цус алдах эрсдэлийн үнэлгээ',19,NULL,NULL,0,0,12,490,NULL),
(@Form,'HASBLED',N'HAS-BLED * (0-9)','Text',NULL,'s19',N'HAS-BLED Цус алдах эрсдэлийн үнэлгээ',19,NULL,NULL,0,0,12,500,NULL),
(@Form,'LaboratoriinShinjilgeeHiisenEseh',N'Лабораторийн шинжилгээ хийсэн эсэх?','RadioBox','f22_14','s20',N'Лабораторийн шинжилгээ',20,NULL,NULL,0,0,12,510,NULL),
(@Form,'TiimBolVndsenShinjilgeeHiisenOgnoog',N'Тийм бол үндсэн шинжилгээ хийсэн огноог бичнэ үү:|_ _/_ _/_ _ _ _| хоног/өдөр/он','RadioBox','f22_17','s20',N'Лабораторийн шинжилгээ',20,NULL,NULL,0,0,12,520,NULL),
(@Form,'HerevVndsenShinjilgeendZarimNegVzvvlelt',N'Хэрэв үндсэн шинжилгээнд зарим нэг үзүүлэлт байхгүй бол','Text',NULL,'s21',N'Шинжилгээний үзүүлэлтүүдийг сонгон доорх хүснэгтийг бөглөнө үү.',21,NULL,NULL,0,0,12,530,NULL),
(@Form,'OdooEmHereglejBaigaaEseh',N'Одоо эм хэрэглэж байгаа эсэх (одоо/эмнэлэгт хэвтэх үед)?','RadioBox','f22_14','s22',N'Эмийн хэрэглээ (Одоо/хэвтэх үед)',22,NULL,NULL,0,0,12,540,NULL),
(@Form,'YamarNegenEmBeldmel',N'Ямар нэгэн эм (Эмнэлэг үзүүлсний дараа эсвэл эмнэлгээс гарсны дараа нэмж бичүүлсэн, үргэлжлүүлэн уусан эм)? бэлдмэл','RadioBox','f22_14','s23',N'Хэрэв тийм бол доорх мэдээллийг бөглөнө үү',23,NULL,NULL,0,0,12,550,NULL),
(@Form,'EmnelegtHevtehVedYamarNegenIntervenshin',N'Эмнэлэгт хэвтэх үед ямар нэгэн интервеншин хийсэн эсэх?','RadioBox','f22_14','s25',N'Интервеншн (тухайн эмнэлэгт хэвтэх үед)',25,NULL,NULL,0,0,12,560,NULL),
(@Form,'AjilbartaiHolbootoiHvndrelGarsanUu',N'Ажилбартай холбоотой хүндрэл гарсан уу?','RadioBox','f22_14','s28',N'Энэ хэсэг зөвхөн хэвтэн эмчлүүлж буй өвчтөнд хамаарна.',28,NULL,NULL,0,0,12,570,NULL),
(@Form,'TiimBolDoorhHvsnegtiigBuglunuVv',N'Тийм бол доорх хүснэгтийг бөглөнө үү','Text',NULL,'s28',N'Энэ хэсэг зөвхөн хэвтэн эмчлүүлж буй өвчтөнд хамаарна.',28,NULL,NULL,0,0,12,580,NULL),
(@Form,'AjilbarynDaraaEmnelegtBaihVedTohioldson',N'Ажилбарын дараа эмнэлэгт байх үед тохиолдсон амь насанд аюулгүй хүндрэлүүд','RadioBox','f22_14','s30',N'Энэ хэсэг зөвхөн хэвтэн эмчлүүлж буй өвчтөнд хамаарна.',30,NULL,NULL,0,0,12,590,NULL),
(@Form,'TiimBolDoorhHvsnegtiigBuglunuVv2',N'Тийм бол доорх хүснэгтийг бөглөнө үү','Text',NULL,'s30',N'Энэ хэсэг зөвхөн хэвтэн эмчлүүлж буй өвчтөнд хамаарна.',30,NULL,NULL,0,0,12,600,NULL),
(@Form,'DvrslelAnalogiinHemjeeUtga',N'Дүрслэл-аналогийн хэмжээ (VAS) утга: (0-ээс 100 хүртэл)','Number',NULL,'s70',N'Би хэт их санаа зовж эсвэл сэтгэл гутарсан',70,NULL,NULL,0,0,12,610,NULL),
(@Form,'HavhlagynChimeeTiimBolAortynHavhlaga',N'Хавхлагын чимээ: Тийм бол: -Аортын хавхлага: - Нарийсал - Регургитаци -Митрал хавхлага: - Нарийсал - Регургитаци -Гурван хавтаст: - Нарийсал - Регургитаци -Уушгины хавхлага: - Нарийсал - Регургитаци','Text',NULL,'s71',N'Зүрх чагналтаар',71,NULL,NULL,0,0,12,620,N' Үгүй Тийм  Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй  Үгүй Тийм Тодорхойгүй'),
(@Form,'UushginyHerjignvvr',N'Уушгины хэржигнүүр','Text',NULL,'s71',N'Зүрх чагналтаар',71,NULL,NULL,0,0,12,630,N' Үгүй Тийм Тодорхойгүй'),
(@Form,'S3MorinTuvurguun',N'S3 морин төвөргөөн','Text',NULL,'s71',N'Зүрх чагналтаар',71,NULL,NULL,0,0,12,640,N' Үгүй Тийм Тодорхойгүй'),
(@Form,'Amsgaadalt',N'Амьсгаадалт','RadioBox','f22_26','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,650,NULL),
(@Form,'IIZereg',N'II зэрэг','Text',NULL,'s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,660,N'Идэвхтэй хөдөлгөөн бага зэрэг хязгаарлагдана. Биеийн хүчний ердийн ачаалалын үед буюу энгийн дасгал хөдөлгөөнд амьсгаадах, ядрах, эсвэл зүрх дэлсэх шинж тэмдэг илэрнэ.'),
(@Form,'IIIZereg',N'III зэрэг','Text',NULL,'s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,670,N'Идэвхтэй хөдөлгөөн мэдэгдэхүйц хязгаарлагдана. Биеийн хүчний ердийнхөөс бага ачаалалын үед шинж тэмдэг илэрнэ, гэхдээ тайван байдалд амьсгаадалт илрэхгүй.'),
(@Form,'IVZereg',N'IV зэрэг','Text',NULL,'s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,680,N'Зовуурь шинж тэмдэг илрэхгүйгээр ямар нэг дасгал хөдөлгөөн хийж чадахгүй. Тайван үед шинж тэмдэг илэрнэ. Ямар нэг дасгал хөдөлгөөн хийвэл бие тавгүй болж зовуурь шинж тэмдэг нэмэгдэнэ.'),
(@Form,'DaraltIhselt',N'Даралт ихсэлт','RadioBox','f22_27','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,690,NULL),
(@Form,'TamhinyHereglee',N'Тамхины хэрэглээ','RadioBox','f22_28','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,700,NULL),
(@Form,'ArhinyHereglee',N'Архины хэрэглээ','RadioBox','f22_29','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,710,NULL),
(@Form,'EmiinHeregleeHamaaral',N'Эмийн хэрэглээ / хамаарал','RadioBox','f22_30','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,720,NULL),
(@Form,'IdevhteiHudulguun',N'Идэвхтэй хөдөлгөөн','RadioBox','f22_31','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,730,NULL),
(@Form,'ChihriinShijin2',N'Чихрийн шижин','RadioBox','f22_32','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,740,NULL),
(@Form,'Dislipidemi',N'Дислипидеми','RadioBox','f22_33','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,750,NULL),
(@Form,'ZvrhSudasnyUvchniiUdamshlynUgvvlemjGenet',N'Зүрх судасны өвчний удамшлын өгүүлэмж Гэнэт нас барах эмгэгийн удамшлын өгүүлэмж (40-өөс доош насны 1 ба түүнээс дээш төрөл садан) Титэм судасны эмгэгийн (ТСЭ) удамшлын өгүүлэмж','RadioBox','f22_34','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,760,NULL),
(@Form,'TosguurynJirvegnee',N'Тосгуурын жирвэгнээ (ТЖ)','RadioBox','f22_35','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,770,NULL),
(@Form,'ZvrhniiDutagdal',N'Зүрхний дутагдал (ЗД)','RadioBox','f22_36','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,780,NULL),
(@Form,'UmnuhHarvaltBaEsvelEmboliVvssen',N'Өмнөх харвалт ба/эсвэл эмболи үүссэн тохиолдол','RadioBox','f22_37','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,790,NULL),
(@Form,'UmnuhTsusAldalt',N'Өмнөх цус алдалт','RadioBox','f22_38','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,800,NULL),
(@Form,'ZahynSudasnyUvchin',N'Захын судасны өвчин*','RadioBox','f22_39','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,810,NULL),
(@Form,'Kardiomiopati',N'Кардиомиопати','RadioBox','f22_40','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,820,NULL),
(@Form,'GvreeniiArteriinTovruu',N'Гүрээний артерийн товруу','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,830,NULL),
(@Form,'DoodMuchniiArteriinUvchin',N'Доод мөчний артерийн өвчин','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,840,NULL),
(@Form,'ZvrhGenetZogsoh',N'Зүрх гэнэт зогсох','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,850,NULL),
(@Form,'PeismeikerZvrhniiDefibrillyatorSuulgats',N'Пэйсмэйкер/ Зүрхний дефибриллятор суулгац (ЗДС)','RadioBox','f22_41','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,860,NULL),
(@Form,'AortynHavhlagadHiisenUmnuhIntervenshin',N'Аортын хавхлагад хийсэн өмнөх интервеншин','RadioBox','f22_42','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,870,NULL),
(@Form,'MitralHavhlagadHiisenUmnuhIntervenshin',N'Митрал хавхлагад хийсэн өмнөх интервеншин','RadioBox','f22_43','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,880,NULL),
(@Form,'GurvanHavtastHavhlagadHiisenUmnuhIntervenshin',N'Гурван хавтаст хавхлагад хийсэн өмнөх интервеншин','RadioBox','f22_44','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,890,NULL),
(@Form,'AortynHavhlagaOdooEmgegteiEseh',N'Аортын хавхлага одоо эмгэгтэй эсэх','RadioBox','f22_45','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,900,NULL),
(@Form,'MitralHavhlagaOdooEmgegteiEseh',N'Митрал хавхлага одоо эмгэгтэй эсэх','RadioBox','f22_46','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,910,NULL),
(@Form,'GurvanHavtastHavhlagaOdooEmgegteiEseh',N'Гурван хавтаст хавхлага одоо эмгэгтэй эсэх','RadioBox','f22_47','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,920,NULL),
(@Form,'TurulhiinUvchinEmgegteiEseh',N'Төрөлхийн өвчин эмгэгтэй эсэх','RadioBox','f22_48','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,930,NULL),
(@Form,'TsusHudlulzvidSaadUchruulahHovdlynHem',N'Цус хөдлөлзүйд саад учруулах ховдлын хэм алдагдал байна уу?','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,940,NULL),
(@Form,'ZvrhSudasnyBusadUvchinEmgegteiEseh',N'Зүрх судасны бусад өвчин эмгэгтэй эсэх','RadioBox','f22_49','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,950,NULL),
(@Form,'BambaiBulchirhainEmgeg',N'Бамбай булчирхайн эмгэг','RadioBox','f22_50','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,960,NULL),
(@Form,'BuurniiArhagUvchin',N'Бөөрний архаг өвчин','RadioBox','f22_51','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,970,NULL),
(@Form,'ElegniiUvchin',N'Элэгний өвчин','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,980,NULL),
(@Form,'UushginyArhagBuglurultUvchin',N'Уушгины архаг бөглөрөлт өвчин (COPD)','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,990,NULL),
(@Form,'NoironDundAmsgalTasaldahEmgeg',N'Нойрон дунд амьсгал тасалдах эмгэг','RadioBox','f22_52','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1000,NULL),
(@Form,'HortHavdar',N'Хорт хавдар','RadioBox','f22_53','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1010,NULL),
(@Form,'RevmatoidArtrit',N'Ревматойд артрит','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1020,NULL),
(@Form,'SetgelGutral',N'Сэтгэл гутрал','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1030,NULL),
(@Form,'TaninMedehvinHotsrogdol',N'Танин мэдэхүйн хоцрогдол','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1040,NULL),
(@Form,'OdooJiremsenVv',N'Одоо жирэмсэн үү?','RadioBox','f22_54','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1050,NULL),
(@Form,'HvniiDarhlalHomsdolynVirusHaldvartaiYuu',N'Хүний дархлал хомсдолын вирус (ХДХВ) халдвартай юу ?','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1060,NULL),
(@Form,'COVID19',N'COVID-19 (одоо халдвартай юу ?)','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1070,NULL),
(@Form,'ArhagAutoimmunUvchin',N'Архаг аутоиммун өвчин','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1080,NULL),
(@Form,'AspirinVlTevchihEmgeg',N'Аспирин үл тэвчих эмгэг','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1090,NULL),
(@Form,'AntikoagulyantEmUuhZaalttaiYuu',N'Антикоагулянт эм уух заалттай юу?','RadioBox','f22_55','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1100,NULL),
(@Form,'TsusAldahErsdelUndurVv',N'Цус алдах эрсдэл өндөр үү? (ARC-HBR)','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1110,NULL),
(@Form,'ZvrhniiHem',N'Зүрхний хэм','RadioBox','f22_56','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1120,NULL),
(@Form,'SupraventrikulyarEkstrasistol',N'Суправентрикуляр экстрасистол','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1130,NULL),
(@Form,'HovdlynEkstrasistol',N'Ховдлын экстрасистол','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1140,NULL),
(@Form,'TosguurHovdlynHorig',N'Тосгуур-ховдлын хориг','RadioBox','f22_57','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1150,NULL),
(@Form,'GisiinHuliinHorig',N'Гисийн хөлийн хориг (BBB)','RadioBox','f22_58','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1160,NULL),
(@Form,'STSegmentiinUurchlultIshemiinShinjvvd',N'ST сегментийн өөрчлөлт, ишемийн шинжүүд','RadioBox','f22_59','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1170,NULL),
(@Form,'UrvuuTShvd',N'Урвуу Т шүд','RadioBox','f22_60','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1180,NULL),
(@Form,'EmgegQShvd',N'Эмгэг Q шүд','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1190,NULL),
(@Form,'DavtanZTsBDeerDinamikUurchlultGarsan',N'Давтан ЗЦБ дээр динамик өөрчлөлт гарсан эсэх','RadioBox','f22_14','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1200,NULL),
(@Form,'ZvrhniiTsohilt',N'Зүрхний цохилт:','RadioBox','f22_17','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1210,NULL),
(@Form,'QRSVrgeljlehHugatsaa',N'QRS- үргэлжлэх хугацаа','RadioBox','f22_17','s72',N'Шинж тэмдэг ба бодит үзлэг',72,NULL,NULL,0,0,12,1220,NULL),
(@Form,'ZvvnHovdlynDiastolynTugsguliinDiametr',N'Зүүн ховдлын диастолын төгсгөлийн диаметр (LVEDD)','RadioBox','f22_17','s73',N'Зүүн ховдол (LV):',73,NULL,NULL,0,0,12,1230,NULL),
(@Form,'ZvvnHovdlynSistolynTugsguliinDiametr',N'Зүүн ховдлын систолын төгсгөлийн диаметр (LVESD)','RadioBox','f22_17','s73',N'Зүүн ховдол (LV):',73,NULL,NULL,0,0,12,1240,NULL),
(@Form,'ZvvnHovdolynTsatsaltynFrakts',N'Зүүн ховдолын цацалтын фракц (LVEF)','RadioBox','f22_17','s73',N'Зүүн ховдол (LV):',73,NULL,NULL,0,0,12,1250,NULL),
(@Form,'ZvvnHovdlynDiastolynTugsguliinEzelhvvn',N'Зүүн ховдлын диастолын төгсгөлийн эзэлхүүн (LVEDV)','RadioBox','f22_17','s73',N'Зүүн ховдол (LV):',73,NULL,NULL,0,0,12,1260,NULL),
(@Form,'ZvvnHovdlynSistolynTugsguliinEzelhvvn',N'Зүүн ховдлын систолын төгсгөлийн эзэлхүүн (LVESV)','RadioBox','f22_17','s73',N'Зүүн ховдол (LV):',73,NULL,NULL,0,0,12,1270,NULL),
(@Form,'ZvvnHovdolynTromb',N'Зүүн ховдолын (LV) тромб','RadioBox','f22_14','s73',N'Зүүн ховдол (LV):',73,NULL,NULL,0,0,12,1280,NULL),
(@Form,'RVTelegdel',N'RV тэлэгдэл','RadioBox','f22_14','s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1290,NULL),
(@Form,'SistolynVeiinUushignyArteriinDaraltygTootsoh',N'Систолын үеийн уушигны артерийн даралтыг тооцох','RadioBox','f22_17','s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1300,NULL),
(@Form,'VnheltsgiinShingen',N'Үнхэлцгийн шингэн','RadioBox','f22_61','s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1310,NULL),
(@Form,'EmgegUurchlultIlersenEseh',N'Эмгэг өөрчлөлт илэрсэн эсэх','RadioBox','f22_62','s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1320,NULL),
(@Form,'Onoo',N'Оноо','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1330,N'Шинж тэмдэг'),
(@Form,'F1',N'□ 1','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1340,N'Байхгүй'),
(@Form,'F2a',N'□ 2а','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1350,N'Хөнгөн'),
(@Form,'F2b',N'□ 2б','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1360,N'Дунд'),
(@Form,'F3',N'□ 3','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1370,N'Хүнд'),
(@Form,'F4',N'□ 4','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1380,N'Хөдөлмөрийн чадвар алдагдасан'),
(@Form,'ErsdeltHvchinZvilsTodorhoilolt',N'Эрсдэлт хүчин зүйлс, тодорхойлолт','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1390,N'Оноо'),
(@Form,'H',N'H','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1400,N'Хяналтгүй АДИӨ Систолын даралт > 160 мм.муб'),
(@Form,'A',N'A','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1410,N'Бөөр, элэгний үйл ажиллагааны алдагдал Диализ, эрхтэн шилжүүлэн суулгасан, сийвэнгийн креатинин >200umol/L, цирроз, билирубин >x2 энгийн дээд хэмжээ, AST/ALT/ALP>x3 энгийн дээд хэмжээ'),
(@Form,'S',N'S','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1420,N'Тархины цус харвалт Тархины цус хомсдолын харвалт, тархины эдийн цус харвалтын түүхтэй'),
(@Form,'B',N'B','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1430,N'Цус алдалтын эсвэл урьтал байдлын түүхтэй Их хэмжээний цус алдалтын түүхтэй, эсвэл хүнд зэргийн тромбоцитопени, цус багадалттай'),
(@Form,'L',N'L','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1440,N'Тогтворгүй INRb К витамины антагонистын эмчилгээ хийлгэж байгаа тохиолдолд TTR<60%'),
(@Form,'E',N'E','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1450,N'Нас >65 эсвэл хэт эмзэг байдал'),
(@Form,'D',N'D','Text',NULL,'s74',N'Баруун ховдол (RV):',74,NULL,NULL,0,0,12,1460,N'Сэтгэц нөлөөт бодис, Согтууруулах ундааны хэрэглээ NSAID эсвэл антиагрегант эмийн замбараагүй хэрэглээ, эсвэл согтууруулах ундааны хэт хэрэглээ (7 хоногоор)'),
(@Form,'Vzvvlelt',N'Үзүүлэлт','Text',NULL,'s75',N'Нийт',75,NULL,NULL,0,0,12,1470,N'Нэгж'),
(@Form,'BNP',N'□ BNP','RadioBox','f22_63','s75',N'Нийт',75,NULL,NULL,0,0,12,1480,NULL),
(@Form,'NTProBNP',N'□ NT-Pro-BNP','RadioBox','f22_63','s75',N'Нийт',75,NULL,NULL,0,0,12,1490,NULL),
(@Form,'HbA1c',N'□ HbA1c','RadioBox','f22_64','s75',N'Нийт',75,NULL,NULL,0,0,12,1500,NULL),
(@Form,'UlunVeiinGlyukoz',N'□ Өлөн үеийн глюкоз','RadioBox','f22_65','s75',N'Нийт',75,NULL,NULL,0,0,12,1510,NULL),
(@Form,'Gemoglobin',N'□ Гемоглобин','RadioBox','f22_66','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1520,NULL),
(@Form,'Gematokrit',N'□ Гематокрит','RadioBox','f22_67','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1530,NULL),
(@Form,'TsusnyUlaanEs',N'□ Цусны улаан эс (RBC)','RadioBox','f22_68','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1540,NULL),
(@Form,'TsagaanTsusnyEs',N'□ Цагаан цусны эс (WBC)','RadioBox','f22_69','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1550,NULL),
(@Form,'YaltasEs',N'□ Ялтас эс','RadioBox','f22_69','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1560,NULL),
(@Form,'TroponinI',N'□ Тропонин I','RadioBox','f22_70','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1570,NULL),
(@Form,'TroponinT',N'□ Тропонин Т','RadioBox','f22_70','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1580,NULL),
(@Form,'HsTroponinI',N'□ Hs Тропонин I','RadioBox','f22_70','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1590,NULL),
(@Form,'HsTroponinT',N'□ Hs Тропонин Т','RadioBox','f22_70','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1600,NULL),
(@Form,'CUrvaljUurag',N'□ C урвалж уураг (CRP)','RadioBox','f22_71','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1610,NULL),
(@Form,'HsCRP',N'□ Hs-CRP:','RadioBox','f22_72','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1620,NULL),
(@Form,'TsusanDahMochevin',N'□ Цусан дахь мочевин (BUN)','RadioBox','f22_73','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1630,NULL),
(@Form,'Mochevin',N'□ Мочевин','RadioBox','f22_73','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1640,NULL),
(@Form,'SKreatinin',N'□ S-креатинин','RadioBox','f22_74','s76',N'□ Глюкозын ачаалалтай сорил',76,NULL,NULL,0,0,12,1650,NULL),
(@Form,'KreatinKinazaMB',N'□ Креатин киназа-МБ (CK-MB)','RadioBox','f22_75','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1660,NULL),
(@Form,'AlaninAminotransferaza',N'□ Аланин аминотрансфераза (ALT)','RadioBox','f22_75','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1670,NULL),
(@Form,'AspartatAminotransferaza',N'□ Аспартат аминотрансфераза (АСТ)','RadioBox','f22_75','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1680,NULL),
(@Form,'GammaGlutamilTranspeptidaza',N'□ Гамма-Глутамил транспептидаза (GGT)','RadioBox','f22_75','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1690,NULL),
(@Form,'ShvltlegFosfataza',N'□ Шүлтлэг фосфатаза','RadioBox','f22_75','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1700,NULL),
(@Form,'LaktatDegidrogenaza',N'□ Лактат дегидрогеназа (LDH)','RadioBox','f22_75','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1710,NULL),
(@Form,'SheesniiHvchil',N'□ Шээсний хүчил','RadioBox','f22_74','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1720,NULL),
(@Form,'NiitHolesterin',N'□ Нийт холестерин','RadioBox','f22_76','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1730,NULL),
(@Form,'LDLHolesterol',N'□ LDL холестерол','RadioBox','f22_76','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1740,NULL),
(@Form,'HDLHolesterol',N'□ HDL холестерол','RadioBox','f22_76','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1750,NULL),
(@Form,'Triglitserid',N'□ Триглицерид','RadioBox','f22_76','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1760,NULL),
(@Form,'TJIinVedUdaanHugatsaandEmchilgeend',N'ТЖ-ийн үед удаан хугацаанд эмчилгээнд хэрэглэгддэг зүрхний хэм алдагдлын эсрэг эмүүд','RadioBox','f22_77','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1770,NULL),
(@Form,'BetaBlokator',N'Бета блокатор','RadioBox','f22_77','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1780,NULL),
(@Form,'VitaminKAntagonistVgviTiimTodorhoigvi',N'Витамин К антагонист (VKA) □ Үгүй □ Тийм □ Тодорхойгүй','RadioBox','f22_78','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1790,NULL),
(@Form,'VitaminKBusUuhAntikoagulyantBeldmel',N'Витамин К бус уух антикоагулянт бэлдмэл (NOAC): □ Үгүй □ Тийм □ Тодорхойгүй','RadioBox','f22_79','s77',N'□ Бөөрний үйл ажиллагаа',77,NULL,NULL,0,0,12,1800,NULL),
(@Form,'BagaMolekultGeparin',N'□ Бага молекулт гепарин (LMWH)','RadioBox','f22_17','s78',N'□ Том молекулт гепарин (UFH)',78,NULL,NULL,0,0,12,1810,NULL),
(@Form,'BusadAntikoagulyantVildelteiEmvvd',N'□ Бусад антикоагулянт үйлдэлтэй эмүүд','Text',NULL,'s78',N'□ Том молекулт гепарин (UFH)',78,NULL,NULL,0,0,12,1820,N'Тодруулах:'),
(@Form,'Aspirin',N'□ Аспирин','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1830,NULL),
(@Form,'Klopidogrel',N'□ Клопидогрел','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1840,NULL),
(@Form,'Prasugrel',N'□ Прасугрел','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1850,NULL),
(@Form,'Kangrelor',N'□ Кангрелор','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1860,NULL),
(@Form,'Tikagrelor',N'□ Тикагрелор','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1870,NULL),
(@Form,'Tiklopidin',N'□ Тиклопидин','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1880,NULL),
(@Form,'Dipiridamol',N'□ Дипиридамол','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1890,NULL),
(@Form,'Tsilostazol',N'□ Цилостазол','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1900,NULL),
(@Form,'BusadYaltasEsiinEsregVildelteiEm',N'□ Бусад ялтас эсийн эсрэг үйлдэлтэй эм','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1910,N'Тодруулах:'),
(@Form,'Statin',N'Статин','RadioBox','f22_80','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1920,NULL),
(@Form,'BusadUuhTosBuuruulahEmvvd',N'Бусад өөх тос бууруулах эмүүд','RadioBox','f22_80','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1930,NULL),
(@Form,'Fibratuud',N'□ Фибратууд','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1940,N'Дэлгэрүүлэх:'),
(@Form,'NikotiniiHvchliinBvleg',N'□ Никотиний хүчлийн бүлэг','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1950,N'Дэлгэрүүлэх:'),
(@Form,'HolesterolShingeeltiigSaatuulagch',N'□ Холестерол шингээлтийг саатуулагч','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1960,N'Дэлгэрүүлэх:'),
(@Form,'PCSK9Saatuulagch',N'□ PCSK9 саатуулагч','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1970,N'Дэлгэрүүлэх:'),
(@Form,'SmallInterferingRNA',N'□ Small interfering RNA (siRNA)','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1980,N'Дэлгэрүүлэх:'),
(@Form,'ReziniiBvlgiinEm',N'□ Резиний бүлгийн эм','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,1990,N'Дэлгэрүүлэх:'),
(@Form,'AngiotenzinHuvirgahFermentiinSaatuulagch',N'Ангиотензин хувиргах ферментийн саатуулагч (АФХС)','RadioBox','f22_80','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,2000,NULL),
(@Form,'Benazepril',N'□ Беназеприл','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,2010,N'Хоногийн нийт тун'),
(@Form,'Kaptopril',N'□ Каптоприл','Text',NULL,'s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,2020,N'[ _ _ _ _] мг'),
(@Form,'Tsilazapril',N'□ Цилазаприл','RadioBox','f22_17','s79',N'Эмчилгээ',79,NULL,NULL,0,0,12,2030,NULL),
(@Form,'AngiotenzinIIRetseptoriinHoriglogch',N'Ангиотензин II рецепторийн хориглогч (АРХ)','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2040,NULL),
(@Form,'MineralokortikoidRetseptorynAntagonist',N'Минералокортикоид рецепторын антагонист (МРА)','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2050,NULL),
(@Form,'BusadSheesHuuhEmvvd',N'Бусад шээс хөөх эмүүд','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2060,NULL),
(@Form,'KaltsiinSuvgiinHoriglogch',N'Кальцийн сувгийн хориглогч (КСХ)','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2070,NULL),
(@Form,'AngiotenzinRetseptorNeprilizinSaatuulagch',N'Ангиотензин рецептор Неприлизин саатуулагч (ARNI)','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2080,NULL),
(@Form,'Ivabradin',N'Ивабрадин','RadioBox','f22_81','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2090,NULL),
(@Form,'BusadDaraltBuuruulahVildelteiEmvvd',N'Бусад даралт бууруулах үйлдэлтэй эмүүд','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2100,NULL),
(@Form,'Nitratuud',N'Нитратууд','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2110,NULL),
(@Form,'KaliinSuvagIdevhjvvlegch',N'Калийн суваг идэвхжүүлэгч','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2120,NULL),
(@Form,'BusadAntianginalBeldmelvvd',N'Бусад антиангинал бэлдмэлүүд','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2130,NULL),
(@Form,'ShuudReninSaatuulagch',N'Шууд ренин саатуулагч (DRI)','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2140,NULL),
(@Form,'BodisynSoliltsoonyBeldmelvvd',N'Бодисын солилцооны бэлдмэлүүд','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2150,NULL),
(@Form,'GlikoproteinIIbIIIaSaatuulagch',N'Гликопротейн IIb/IIIa саатуулагч','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2160,NULL),
(@Form,'UsturugchiinShahuurgaSaatuulagch',N'Устөрөгчийн шахуурга саатуулагч (PPI)','RadioBox','f22_14','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2170,NULL),
(@Form,'TsusanDahGlyukozBuuruulahEm',N'Цусан дахь глюкоз бууруулах эм?','RadioBox','f22_80','s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2180,NULL),
(@Form,'ChihriinShijingiinEsregUuhEmvvd',N'□ Чихрийн шижингийн эсрэг уух эмүүд','Text',NULL,'s90',N'□ Бусад, тодруулна уу:',90,NULL,NULL,0,0,12,2190,N'Дэлгэрүүлэх:'),
(@Form,'UujHeregledeggviGlyukagonTustPeptid1',N'□ Ууж хэрэглэдэггүй глюкагон төст пептид 1 (GLP-1) агонист','RadioBox','f22_82','s91',N'□ Инсулин',91,NULL,NULL,0,0,12,2200,NULL),
(@Form,'JilBvriiTomuugiinEsregDarhlaajuulalt',N'Жил бүрий томуугийн эсрэг дархлаажуулалт','RadioBox','f22_14','s91',N'□ Инсулин',91,NULL,NULL,0,0,12,2210,NULL),
(@Form,'KatetrAblatsiEmchilgee',N'Катетр аблаци эмчилгээ','RadioBox','f22_83','s91',N'□ Инсулин',91,NULL,NULL,0,0,12,2220,NULL),
(@Form,'PeismeikerSuulgats',N'Пэйсмэйкер суулгац','RadioBox','f22_84','s91',N'□ Инсулин',91,NULL,NULL,0,0,12,2230,NULL),
(@Form,'KardioverterDefibrillyatorSuulgats',N'Кардиовертер-дефибриллятор (ICD) суулгац','RadioBox','f22_85','s91',N'□ Инсулин',91,NULL,NULL,0,0,12,2240,NULL),
(@Form,'TitemSudasnyMesZasal',N'Титэм судасны мэс засал (CABG)','RadioBox','f22_86','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2250,NULL),
(@Form,'ZvrhniiHavhlagynIntervenshin',N'Зүрхний хавхлагын интервеншин','RadioBox','f22_86','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2260,NULL),
(@Form,'HovdlygDemjihTuhuurumjSuulgasanUu',N'Ховдлыг дэмжих төхөөрөмж суулгасан уу?','RadioBox','f22_86','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2270,NULL),
(@Form,'SudasnyMesZasalHiisenVv',N'Судасны мэс засал хийсэн үү?','RadioBox','f22_86','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2280,NULL),
(@Form,'TitemSudsanDotuurhEmchilgee',N'Титэм судсан дотуурх эмчилгээ (ТиСДЭ)','RadioBox','f22_87','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2290,NULL),
(@Form,'SudsanDotuurZvrhniiHavhlagaZasahAjilbar',N'Судсан дотуур зүрхний хавхлага засах ажилбар','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2300,NULL),
(@Form,'MesZaslynDaraahZvrhniiShigdees',N'Мэс заслын дараах зүрхний шигдээс (шинээр эмгэг Q шүд илрэх)','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2310,NULL),
(@Form,'Mediastinit',N'Медиастинит','RadioBox','f22_88','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2320,NULL),
(@Form,'Endokardit',N'Эндокардит','RadioBox','f22_88','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2330,NULL),
(@Form,'Tamponad',N'Тампонад','RadioBox','f22_88','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2340,NULL),
(@Form,'TsusAldalt',N'Цус алдалт','RadioBox','f22_89','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2350,NULL),
(@Form,'TomSudasnyHvndrelvvd',N'Том судасны хүндрэлүүд','RadioBox','f22_88','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2360,NULL),
(@Form,'Tromboemboli',N'Тромбоэмболи','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2370,NULL),
(@Form,'UrhagVldetsBvhiiTarhinyTsusHarvalt',N'Урхаг үлдэц бүхий тархины цус харвалт','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2380,NULL),
(@Form,'TsusZadral',N'Цус задрал','RadioBox','f22_88','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2390,NULL),
(@Form,'BusadAjilbarynHvndrelvvd',N'Бусад ажилбарын хүндрэлүүд','RadioBox','f22_90','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2400,NULL),
(@Form,'HarvaltEsvelTsusErgeltiinEmboli',N'Харвалт эсвэл цус эргэлтийн эмболи','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2410,NULL),
(@Form,'TsusAldahHvndrel',N'Цус алдах хүндрэл','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2420,NULL),
(@Form,'BusadZvrhSudasnyUvchlul',N'Бусад зүрх судасны өвчлөл','RadioBox','f22_14','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2430,NULL),
(@Form,'ZvrhSudasnyBusUvchlul',N'Зүрх судасны бус өвчлөл','RadioBox','f22_91','s92',N'Бусад интервеншин: □ Үгүй □ Тийм бол дэлгэрүүлнэ үү: □ Тодорхойгүй',92,NULL,NULL,0,0,12,2440,NULL);

COMMIT;
GO
SET NOEXEC OFF;
GO
SELECT '2.2' AS FormCode, COUNT(*) AS Fields FROM dbo.TenderFormField WHERE FormCode='2.2';
GO
