const { Models } = require('../../config/DB');
const Model = Models.HavhlagiinEmgeg;

function HavhlagaEmgegConfig() {
  this.Fields = [
    [
      { Name: 'id', Label: 'Id', Type: 'Text' },
      { Name: 'patientId', Label: 'Patient id', Type: 'Number' },
      {
        Name: 'togtmolEmTaria',
        Label: 'Тогтмол хэрэглэж байгаа эм, тариа',
        Type: 'Text',
      },
      {
        Name: 'harvalt',
        Label: 'Харвалт',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      { Name: 'date', Label: 'Огноо', Type: 'Text' },

      { Name: 'bloodWbc', Label: 'WBC', Type: 'Text' },
      { Name: 'bloodRbc', Label: 'RBC', Type: 'Text' },
      { Name: 'bloodHb', Label: 'Hb', Type: 'Text' },
      { Name: 'bloodHct', Label: 'HCT', Type: 'Text' },
      { Name: 'bloodPlt', Label: 'PLT', Type: 'Text' },
      { Name: 'bloodPt', Label: 'PT', Type: 'Text' },
      { Name: 'bloodInr', Label: 'INR', Type: 'Text' },
      { Name: 'bloodFibrinogen', Label: 'fibrinogen', Type: 'Text' },
      { Name: 'bloodTt', Label: 'TT', Type: 'Text' },
      { Name: 'bloodAptt', Label: 'APTT', Type: 'Text' },

      { Name: 'buurMochevin', Label: 'Мочевин', Type: 'Text' },
      { Name: 'buurKreatinin', Label: 'Креатинин', Type: 'Text' },
      { Name: 'buurAslo', Label: 'ASLO', Type: 'Text' },
      { Name: 'buurCrb', Label: 'CRB', Type: 'Text' },
      { Name: 'buurRf', Label: 'RF', Type: 'Text' },

      { Name: 'elegUurag', Label: 'Нийт уураг (г/л)', Type: 'Text' },
      { Name: 'elegAlibumin', Label: 'Альбумин', Type: 'Text' },
      { Name: 'elegAsat', Label: 'АСАТ', Type: 'Text' },
      { Name: 'elegAlat', Label: 'АЛАТ', Type: 'Text' },
      { Name: 'elegBilurebin', Label: 'Нийт Билирубин', Type: 'Text' },
      { Name: 'elegGgt', Label: 'ГГТ', Type: 'Text' },
      { Name: 'elegGlyucoz', Label: 'Глюкоз', Type: 'Text' },
      {
        Name: 'virusHbsAg',
        Label: 'HbsAg',
        Type: 'RadioBox',
        OptionType: 'virusHbsAg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'virusHcv',
        Label: 'HCV',
        Type: 'RadioBox',
        OptionType: 'virusHbsAg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'virusTembuu',
        Label: 'Тэмбүү',
        Type: 'RadioBox',
        OptionType: 'virusHbsAg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'virusHiv',
        Label: 'HIV',
        Type: 'RadioBox',
        OptionType: 'virusHbsAg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },

      { Name: 'zvrhTsahBichDate', Label: 'Огноо', Type: 'Text' },
      {
        Name: 'zvrhTsahBichHemnel',
        Label: 'Хэмнэл',
        Type: 'Text',
        OptionType: 'zvrhTsahBichHemnel',
        Config: { IdField: 'Value', TextField: 'Label' },
      },

      { Name: 'zvrhEchoDate', Label: 'Огноо', Type: 'Text' },
      { Name: 'zvrhEchoLvdd', Label: 'LVDd', Type: 'Text' },
      { Name: 'zvrhEchoLvds', Label: 'LVDs', Type: 'Text' },
      { Name: 'zvrhEchoIvsd', Label: 'IVSd', Type: 'Text' },
      { Name: 'zvrhEchoPwd', Label: 'PWd', Type: 'Text' },
      { Name: 'zvrhEchoLvmassi', Label: 'LVmassi', Type: 'Text' },
      { Name: 'zvrhEchoLvef', Label: 'LVEF (Simpson method)', Type: 'Text' },
      { Name: 'zvrhEchoLvgls', Label: 'LV GLS', Type: 'Text' },
      { Name: 'zvrhEchoLavolume', Label: 'LA volume', Type: 'Text' },
      { Name: 'zvrhEchoEeMed', Label: 'E/e’ Med', Type: 'Text' },
      { Name: 'zvrhEchoEeLat', Label: 'E/e’ Lat', Type: 'Text' },
      { Name: 'zvrhEchoDundajEe', Label: 'Дундаж E/e’', Type: 'Text' },
      { Name: 'zvrhEchoTaslavchE', Label: 'Таславч e’', Type: 'Text' },
      { Name: 'zvrhEchoHajuuHanaE', Label: 'Хажуу хана e’', Type: 'Text' },
      {
        Name: 'zvrhEchoUushigArterDaralt',
        Label: 'Уушгины артерийн систолын даралт',
        Type: 'Text',
      },
      { Name: 'zvrhEchoTapse', Label: 'TAPSE (mm)', Type: 'Text' },
      { Name: 'zvrhEchoRvFac', Label: 'RV FAC', Type: 'Text' },
      {
        Name: 'havhlagaNariisal',
        Label: '2 Хавтаст хавхлагын нарийсал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaNariisalEmgegShaltgaan',
        Label: 'Хавхлагын эмгэгийн шалтгаан',
        Type: 'Text',
        OptionType: 'havhlagaNariisalEmgegShaltgaan',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaNariisalHvndinZereg',
        Label: 'Хүндийн зэрэг',
        Type: 'RadioBox',
        OptionType: 'hf_level',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaNariisalOngoiltinSPlanometry',
        Label: '2 хавтаст хавхлагын онгойлтын талбай (planometry)',
        Type: 'Text',
      },
      {
        Name: 'havhlagaNariisalOngoiltinS',
        Label: '2 хавтаст хавхлагын онгойлтын талбай ',
        Type: 'Text',
      },
      { Name: 'havhlagaNariisalPnt', Label: '(PNT)', Type: 'Text' },
      { Name: 'havhlagaNariisalMvPg', Label: 'MV mean PG', Type: 'Text' },
      { Name: 'havhlagaNariisalMvPht', Label: 'MV PHT', Type: 'Text' },
      {
        Name: 'havhlagaNariisalVilkinsDate',
        Label: 'Вилкинсийн шалгуур оноо',
        Type: 'Text',
      },
      {
        Name: 'havhlagaDutagdal',
        Label: '2 Хавтаст хавхлагын дутагдал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaDutagdalEmgegShaltgaan',
        Label: 'Хавхлагын эмгэгийн шалтгаан',
        Type: 'Text',
        OptionType: 'havhlagaDutagdalEmgegShaltgaan',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaDutagdalHvndinZereg',
        Label: 'Хүндийн зэрэг',
        Type: 'RadioBox',
        OptionType: 'hf_level',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      { Name: 'havhlagaDutagdalMrEroa', Label: 'MR EROA', Type: 'Text' },
      {
        Name: 'havhlagaDutagdalMrVenaContract',
        Label: 'MR Vena contract',
        Type: 'Text',
      },
      { Name: 'havhlagaDutagdalMrVolume', Label: 'MR Volume', Type: 'Text' },
      {
        Name: 'havhlagaDutagdalMrFractionRate',
        Label: 'MR Fraction rate',
        Type: 'Text',
      },
      {
        Name: 'havhlagaDutagdalMrZvvnTosgurEzlehHuwi',
        Label: 'MR урсгалын зүүн тосгуурт эзлэх хувь',
        Type: 'Text',
      },
      {
        Name: 'havhlagaNariisalGol',
        Label: 'Гол судасны хавхлагын нарийсал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaNariisalGolEmgegShaltgaan',
        Label: 'Хавхлагын эмгэгийн шалтгаан',
        Type: 'Text',
        OptionType: 'havhlagaNariisalGolEmgegShaltgaan',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaNariisalGolHvndiinZereg',
        Label: 'Хүндийн зэрэг',
        Type: 'RadioBox',
        OptionType: 'hf_level',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaNariisalGolOngoiltiinSPlanometry',
        Label: 'Гол судасны хавхлагын онгойлтын талбай (planometry)',
        Type: 'Text',
      },
      {
        Name: 'havhlagaNariisalGolAovMeanPg',
        Label: 'AoV mean PG',
        Type: 'Text',
      },
      { Name: 'havhlagaNariisalGolAovVMax', Label: 'AoV V max', Type: 'Text' },
      {
        Name: 'havhlagaNariisalGolAovPgMax',
        Label: 'AoV PG max',
        Type: 'Text',
      },
      {
        Name: 'havhlagaDutagdalGol',
        Label: 'Гол судасны хавхлагын дутагдал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaDutagdalGolEmgegShaltgaan',
        Label: 'Хавхлагын эмгэгийн шалтгаан',
        Type: 'Text',
        OptionType: 'havhlagaNariisalGolEmgegShaltgaan',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaDutagdalGolHvndiinZereg',
        Label: 'Хүндийн зэрэг',
        Type: 'RadioBox',
        OptionType: 'hf_level',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      { Name: 'havhlagaDutagdalGolAoRegPht', Label: 'AoReg PHT', Type: 'Text' },
      { Name: 'havhlagaDutagdalGolAorVol', Label: 'AoR vol', Type: 'Text' },
      { Name: 'havhlagaDutagdalGolAorEroa', Label: 'AoR EROA', Type: 'Text' },
      { Name: 'titemSudasDate', Label: 'Огноо', Type: 'Text' },
      {
        Name: 'titemSudasDvgnel',
        Label: 'Дүгнэлт',
        Type: 'Text',
        OptionType: 'titemSudasDvgnel',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'otherTseejniRentgenKti',
        Label: 'Цээжний рентген зураг: КТИ тодорхойлох',
        Type: 'Text',
      },
      { Name: 'golSudasKomAgatsoniDate', Label: 'Агатсоны оноо', Type: 'Text' },
      { Name: 'golSudasKomKalitsinDate', Label: 'Кальцийн оноо', Type: 'Text' },
      {
        Name: 'tsusChanarNyanIlersen',
        Label: 'Нян илэрсэн эсэх',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tsusChanarNyanIlersenTurul',
        Label: 'Нян / төрөл зүйлийг бичих',
        Type: 'Text',
      },
      {
        Name: 'tarhiZvrhTomoEurScoreLogistic',
        Label: 'EuroScore Logistic',
        Type: 'Text',
      },
      { Name: 'tarhiZvrhTomoJin', Label: 'Жин (кг)', Type: 'Text' },
      { Name: 'tarhiZvrhTomoUndur', Label: 'Өндөр (см)', Type: 'Text' },
      {
        Name: 'tarhiZvrhTomoTamhi',
        Label: 'Тамхи',
        Type: 'RadioBox',
        OptionType: 'hf_tamhi',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoChiherShijin',
        Label: 'Чихрийн шижин',
        Type: 'RadioBox',
        OptionType: 'tarhiZvrhTomoChiherShijin',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoArterDaraltIhselt',
        Label: 'Артерийн даралт ихсэлт',
        Type: 'RadioBox',
        OptionType: 'vvd_artreriin_daralt_ihselt',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoUuhTosSoliltsoo',
        Label: 'Өөх тосны солилцооны өөрчлөлт',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoBuurniEmgeg',
        Label: 'Бөөрний эмгэг',
        Type: 'RadioBox',
        OptionType: 'vvd_buurnii_emgeg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoUushigArhagUvchin',
        Label: 'Уушгины архаг өвчин',
        Type: 'RadioBox',
        OptionType: 'tarhiZvrhTomoUushigArhagUvchin',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoBusadSudasEmgeg',
        Label: 'Бусад судасны эмгэг',
        Type: 'RadioBox',
        OptionType: 'tarhiZvrhTomoBusadSudasEmgeg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoTarhiSudasEmgeg',
        Label: 'Тархины судасны эмгэг',
        Type: 'RadioBox',
        OptionType: 'tarhiZvrhTomoTarhiSudasEmgeg',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoMedrelVAAldagdal',
        Label: 'Мэдрэлийн үйл ажиллагааны алдагдал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoGvreeniArterShum',
        Label: 'Гүрээний артерийн шум (Carotid bruits)',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'tarhiZvrhTomoMesZasalUmnuhZvrhniHemnel',
        Label: 'Мэс заслын өмнөх зүрхний хэмнэл',
        Type: 'Text',
        OptionType: 'tarhiZvrhTomoMesZasalUmnuhZvrhniHemnel',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahGolSudasNarisal',
        Label: 'Гол судасны хавхлага нарийсал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahGolSudasDutagdal',
        Label: 'Гол судасны хавхлага дутагдал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahGolSudasMesAjilbar',
        Label: 'Гол судасны хавхлагын мэс ажилбар',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasMesAjilbar',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahGolSudasImplantTurul',
        Label: 'Гол судасны хавхлага имплантын төрөл',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasImplantTurul',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahMitraliNariisal',
        Label: 'Митраль хавхлага нарийсал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahMitraliDutagdal',
        Label: 'Митраль хавхлага дутагдал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahMitraliMesAjilbar',
        Label: 'Митраль хавхлагын мэс ажилбар',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasMesAjilbar',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahMitralImplantTurul',
        Label: 'Митраль хавхлага имплантын төрөл',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahMitralImplantTurul',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraah3HHNariisal',
        Label: '3 хавтаст хавхлага (трикуспид) нарийсал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraah3HHDutagdal',
        Label: '3 хавтаст хавхлага (трикуспид) дутагдал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraah3HHMesAjilbar',
        Label: '3 хавтаст  (трикуспид) хавхлагын мэс ажилбар',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasMesAjilbar',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraah3HHImplantinTurul',
        Label: '3 хавтаст хавхлага (трикуспид) имплантын төрөл',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahMitralImplantTurul',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahUANariisal',
        Label: 'УА-н хавхлага нарийсал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahUADutagdal',
        Label: 'УА-н хавхлага дутагдал',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasNarisal',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahUAMesAjilbar',
        Label: 'УА-н хавхлагын мэс ажилбар',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahGolSudasMesAjilbar',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahUAImplantTurul',
        Label: 'УА-н хавхлага имплантын төрөл',
        Type: 'RadioBox',
        OptionType: 'havhlagaMZDaraahUAImplantTurul',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'havhlagaMZDaraahImplantCode',
        Label: 'Имплантын код',
        Type: 'Text',
      },
      {
        Name: 'implantStJudeMedical',
        Label: 'St.Jude Medical',
        Type: 'RadioBox',
        OptionType: 'vvd_implant_hemjee_st_jude_medical',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'implantMedtronic',
        Label: 'Medtronic',
        Type: 'RadioBox',
        OptionType: 'vvd_implant_hemjee_medtronic',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'bentalMesAjilbar',
        Label: 'Бентал мэс ажилбар',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'devidMesAjilbar',
        Label: 'Дэвид мэс ажилбар',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'mesZDaraahHvndrelTsusAldalt',
        Label: 'Цус алдагдал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'mesZDaraahHvndrelHemAldagdal',
        Label: 'Хэм алдагдал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'mesZDaraahHvndrelTarhiTsusHarvalt',
        Label: 'Тархины цус харвалт',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'mesZDaraahHvndrelOlonErhtniDutagdal',
        Label: 'Олон эрхтэний дутагдал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'mesZDaraahHvndrelVjil',
        Label: 'Үжил',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'mesZDaraahHyanaltEHOKGHyanalt',
        Label: 'Мэс заслын дараах ЭХОКГ хяналт',
        Type: 'RadioBox',
        OptionType: 'vvd_mes_zasliin_daraakh_ehokg_hynalt',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'hiimelHavhlagaTutulHemjee',
        Label: 'Хиймэл хавхлагын төрөл, хэмжээ',
        Type: 'Text',
      },
      {
        Name: 'hiimelHavhlagaMesZasalDate',
        Label: 'Мэс засал хийгдсэн огноо',
        Type: 'Text',
      },
      { Name: 'hiimelHavhlagaADDeed', Label: 'АД систол', Type: 'Text' },
      { Name: 'hiimelHavhlagaADDood', Label: 'АД диастол', Type: 'Text' },
      { Name: 'hiimelHavhlagaPulis', Label: 'Пульс', Type: 'Text' },
      { Name: 'hiimelHavhlagaUndur', Label: 'Өндөр (см)', Type: 'Text' },
      { Name: 'hiimelHavhlagaJin', Label: 'Жин (кг)', Type: 'Text' },
      {
        Name: 'hiimelHavhlagaBieJinIndex',
        Label: 'биеийн жингийн индекс',
        Type: 'Text',
      },
      {
        Name: 'hiimelHavhlagaHGUrsgal',
        Label: 'Хавхлагын гадуурх урсгал',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'hiimelHavhlagaBvtetsHudulguun',
        Label: 'Хиймэл хавхлагын бүтэц, хөдөлгөөн',
        Type: 'RadioBox',
        OptionType: 'vvd_hiimel_bvtets_hudulguun',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      {
        Name: 'hiimelHavhlagaDundajDaralt',
        Label: 'Хиймэл хавхлагын дундаж даралт (mean PG)',
        Type: 'Text',
      },
      {
        Name: 'hiimelHavhlagaRegurgitatsHvndZereg',
        Label: 'Регургитацийн хүндийн зэрэг',
        Type: 'Text',
      },
      {
        Name: 'hiimelHavhlagaZvvnTosguur',
        Label: 'Зүүн тосгуур',
        Type: 'Text',
      },
      { Name: 'hiimelHavhlagaZvvnHovdol', Label: 'зүүн ховдлын', Type: 'Text' },
      {
        Name: 'hiimelHavhlagaZvvnHovdolAgshihChadvar',
        Label: 'Зүүн ховдлын агших чадвар',
        Type: 'Text',
      },
      {
        Name: 'hiimelHavhlagaUADihselt',
        Label: 'УАД ихсэлт',
        Type: 'RadioBox',
        OptionType: 'yorn_mn',
        Config: { IdField: 'Value', TextField: 'Label' },
      },
      { Name: 'hiimelHavhlagaSpap', Label: 'SPAP', Type: 'Text' },
      { Name: 'inr', Label: 'INR', Type: 'Text' },
    ],
  ];

  this.ObjectName = 'HavhlagiinEmgeg';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id';
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Хавхлага эмгэг',
    NewObjectTitle: 'Хавхлага эмгэг үүсгэх',
    EditObjectTitle: 'Хавхлага эмгэг засах',
  };
}

module.exports = HavhlagaEmgegConfig;
