/**
 * Writing a notification, and ringing whatever the recipient is holding.
 *
 * TWO BUGS THIS FIXES, both of which made patient notifications impossible.
 *
 * 1. The guard read `if (Data && LogedUser && Data.ToUserId)`. ToUserId is the
 *    STAFF recipient, so anything addressed to a patient fell straight through
 *    and returned undefined - silently, with no log line.
 *
 * 2. It wrote through BaseControllerHelper.BaseCreate, whose first act is
 *    PatientScope.ApplyPatientOwnership. During a PATIENT's session that
 *    refused the write outright, because Notification had no SCOPE_BY_OBJECT
 *    entry - so a notification generated by something a patient did (filing an
 *    e-visit request, asking a question) was dropped before it was written.
 *
 *    Adding a scope entry does not fix that; it makes it worse. The function
 *    assigns `Data[scope.Field] = value`, so a notification a patient's action
 *    generates FOR A DOCTOR would be re-addressed to the patient, and the
 *    doctor would never hear about it.
 *
 *    So writes go through Models.Notification.create directly. Notification is
 *    the newer generation - Id primary key, no rec_status, no id_group, no
 *    user_mod - so the only things ModelHelper was contributing were CreateDate
 *    and CreateUserId, which are stamped here. The SCOPE_BY_OBJECT entry that
 *    now exists is for READS: it lets a patient list their own notifications.
 */

const NotificationSocket = require('../WebSockets/NotificationSocket');
const ObjectHelper = require('./ObjectHelper');
const PushHelper = require('./PushHelper');
const { Models } = require('../config/DB');

class NotificationHelper {
  /**
   * Persist a notification and, optionally, push it in real time.
   *
   * Signature unchanged - AdviceController calls this in three places. What
   * changed is that a Data carrying ToPatientId is no longer ignored.
   */
  SaveNotification = async function ({ Data, LogedUser, SendNotification }) {
    try {
      if (!Data || !LogedUser) return null;
      if (!Data.ToUserId && !Data.ToPatientId && !Data.ToDoctorId) {
        // Nobody to tell. Worth a line, because the old code reached this state
        // constantly and said nothing.
        console.error('[NotificationHelper] no recipient on notification, dropped');
        return null;
      }

      const Row = Object.assign({}, Data, {
        CreateDate: Data.CreateDate || ObjectHelper.getDateYMDHMS(),
        CreateUserId: Data.CreateUserId || LogedUser.Id || null,
      });

      const created = await Models.Notification.create(Row);
      const NotificationId = created ? created.Id : null;
      if (!NotificationId) return null;

      if (SendNotification === true) {
        // Route by recipient. NotificationSocket already takes a UserType and
        // defaults it to 'S', so patients only needed to be passed one - no
        // socket change was required.
        if (Data.ToPatientId) {
          NotificationSocket.SendNotification({
            UserType: 'P',
            UserId: Data.ToPatientId,
            Data: NotificationId,
          });
        }
        if (Data.ToUserId) {
          NotificationSocket.SendNotification({
            UserType: 'S',
            UserId: Data.ToUserId,
            Data: NotificationId,
          });
        }
      }

      return NotificationId;
    } catch (ex) {
      console.error('[NotificationHelper] SaveNotification: ' + ex.message);
      return null;
    }
  };

  /**
   * The wrapper producers call to tell a patient something.
   *
   * Writes the bell row, emits over the socket for an app that is open, and
   * makes one best-effort push attempt for one that is not. The push is awaited
   * so its failure is logged against this request, but PushHelper never throws
   * and its result is never checked - a silent phone must not fail the clinical
   * action that triggered it.
   */
  NotifyPatient = async function ({
    PatientId,
    Notes,
    NotesMn,
    Action,
    LinkObjectName,
    LinkObjectId,
    Url,
    ExpiredDate,
    LogedUser,
    Push,
  }) {
    if (!PatientId) return null;

    const Id = await this.SaveNotification({
      Data: {
        ToPatientId: PatientId,
        Notes: Notes || null,
        NotesMn: NotesMn || null,
        Action: Action || null,
        LinkObjectName: LinkObjectName || null,
        LinkObjectId: LinkObjectId || null,
        Url: Url || null,
        ExpiredDate: ExpiredDate || null,
      },
      LogedUser: LogedUser || {},
      SendNotification: true,
    });

    if (Id && Push !== false) {
      await PushHelper.Send({
        UserType: 'P',
        UserId: PatientId,
        Title: 'MnCardio',
        // The Mongolian text is what the patient reads; Notes is the English
        // developer-facing label and is not shown to anyone.
        Body: NotesMn || Notes || '',
        Data: {
          notificationId: Id,
          linkObjectName: LinkObjectName || '',
          linkObjectId: LinkObjectId || '',
          action: Action || '',
        },
      });
    }

    return Id;
  };

  /** The staff equivalent, so producers do not hand-build a Data object. */
  NotifyUser = async function ({
    UserId,
    Notes,
    NotesMn,
    Action,
    LinkObjectName,
    LinkObjectId,
    Url,
    LogedUser,
    Push,
  }) {
    if (!UserId) return null;

    const Id = await this.SaveNotification({
      Data: {
        ToUserId: UserId,
        Notes: Notes || null,
        NotesMn: NotesMn || null,
        Action: Action || null,
        LinkObjectName: LinkObjectName || null,
        LinkObjectId: LinkObjectId || null,
        Url: Url || null,
      },
      LogedUser: LogedUser || {},
      SendNotification: true,
    });

    if (Id && Push !== false) {
      await PushHelper.Send({
        UserType: 'S',
        UserId,
        Title: 'MnCardio',
        Body: NotesMn || Notes || '',
        Data: {
          notificationId: Id,
          linkObjectName: LinkObjectName || '',
          linkObjectId: LinkObjectId || '',
          action: Action || '',
        },
      });
    }

    return Id;
  };
}

module.exports = new NotificationHelper();
