/**
 * Writing a notification, and ringing whatever the recipient is holding.
 *
 * TWO BUGS THIS FIXES, both of which made patient notifications impossible.
 *
 * 1. The guard read `if (Data && LogedUser && Data.ToUserId)`. ToUserId is the
 *    STAFF recipient, so anything addressed to a patient fell straight through
 *    and returned undefined - silently, with no log line.
 *
 * 2. It wrote through BaseControllerHelper.BaseCreate, whose first act is
 *    PatientScope.ApplyPatientOwnership. During a PATIENT's session that
 *    refused the write outright, because Notification had no SCOPE_BY_OBJECT
 *    entry - so a notification generated by something a patient did (filing an
 *    e-visit request, asking a question) was dropped before it was written.
 *
 *    Adding a scope entry does not fix that; it makes it worse. The function
 *    assigns `Data[scope.Field] = value`, so a notification a patient's action
 *    generates FOR A DOCTOR would be re-addressed to the patient, and the
 *    doctor would never hear about it.
 *
 *    So writes go through Models.Notification.create directly. Notification is
 *    the newer generation - Id primary key, no rec_status, no id_group, no
 *    user_mod - so the only things ModelHelper was contributing were CreateDate
 *    and CreateUserId, which are stamped here. The SCOPE_BY_OBJECT entry that
 *    now exists is for READS: it lets a patient list their own notifications.
 */

const NotificationSocket = require('../WebSockets/NotificationSocket');
const ObjectHelper = require('./ObjectHelper');
const PushHelper = require('./PushHelper');
const { Models } = require('../config/DB');

/**
 * Seen IS '1' OR NULL. Measured on MnCardio_test 2026-09-14 - those are the
 * only two values in the column. Nothing in this repo writes it; the nightly
 * EXEC spUpdateNotification does, and its body lives in the database rather
 * than here. The web bell reads the same column, so this must not invent a
 * third value like 'y' or 'true'.
 *
 * It lives here rather than in either api controller because the patient and
 * doctor surfaces both read it, and a notification that is unread on one screen
 * and read on the other would be worse than either behaviour on its own.
 */
const SEEN = '1';

class NotificationHelper {
  /** The stored value that means "read". Compare against it, never assign 'y'. */
  SEEN = SEEN;

  /**
   * One row as the mobile app receives it, identical on /api/patient and
   * /api/doctor.
   *
   * Two things the client depends on and this guarantees:
   *   - `Seen` is a BOOLEAN out here even though the column is a string
   *   - `NotesMn` is the display text; `Notes` is an English developer label
   *     and is never shown to a user
   *
   * LinkObjectName + LinkObjectId are the deep link: VisitComments -> the
   * questions thread, RemoteVisit -> the e-visit, Advice -> the advice item.
   *
   * PatientId and AdviceId are the parent the app navigates to, filled by
   * ShapePage. A VisitComments id alone does not say whose thread it is, and
   * an AdviceComment id does not say which ticket - so a tap landed on the
   * monitoring list instead of the question. null when not applicable.
   */
  Shape = (r) => ({
    Id: r.Id,
    Notes: r.Notes,
    NotesMn: r.NotesMn,
    Action: r.Action,
    LinkObjectName: r.LinkObjectName,
    LinkObjectId: r.LinkObjectId,
    PatientId: r.PatientId || null,
    AdviceId: r.AdviceId || null,
    Url: r.Url,
    Seen: r.Seen === SEEN,
    SeenDate: r.SeenDate,
    CreateDate: r.CreateDate,
  });

  /**
   * Shape a page of raw rows, resolving each deep link's parent first.
   *
   * Resolved at READ time rather than stored: Notification has no column for
   * it, adding one is DDL on the customer's table, and a stored value would
   * leave every notification written before today without it. This costs at
   * most three indexed primary-key lookups per page, whatever its size.
   *
   * A lookup failure costs the ids, never the list.
   */
  ShapePage = async (rows) => {
    try {
      const ids = (name) => [
        ...new Set(
          rows.filter((r) => r.LinkObjectName === name && r.LinkObjectId).map((r) => r.LinkObjectId)
        ),
      ];
      const questionIds = ids('VisitComments');
      const commentIds = ids('AdviceComment');

      const [questions, comments] = await Promise.all([
        questionIds.length
          ? Models.VisitComments.findAll({
              where: { id_data: questionIds },
              attributes: ['id_data', 'patient_id'],
              raw: true,
            })
          : [],
        commentIds.length
          ? Models.AdviceComment.findAll({
              where: { id_data: commentIds },
              attributes: ['id_data', 'adv_com_id_adv'],
              raw: true,
            })
          : [],
      ]);

      const questionPatient = new Map(questions.map((q) => [q.id_data, q.patient_id]));
      const commentAdvice = new Map(comments.map((c) => [c.id_data, c.adv_com_id_adv]));

      const adviceIds = [
        ...new Set([...ids('Advice'), ...comments.map((c) => c.adv_com_id_adv).filter(Boolean)]),
      ];
      const advices = adviceIds.length
        ? await Models.Advice.findAll({
            where: { id_data: adviceIds },
            attributes: ['id_data', 'adv_id_patient'],
            raw: true,
          })
        : [];
      const advicePatient = new Map(advices.map((a) => [a.id_data, a.adv_id_patient]));

      for (const r of rows) {
        if (r.LinkObjectName === 'VisitComments') {
          r.PatientId = questionPatient.get(r.LinkObjectId) || null;
        } else if (r.LinkObjectName === 'AdviceComment') {
          r.AdviceId = commentAdvice.get(r.LinkObjectId) || null;
          r.PatientId = advicePatient.get(r.AdviceId) || null;
        } else if (r.LinkObjectName === 'Advice') {
          r.AdviceId = r.LinkObjectId || null;
          r.PatientId = advicePatient.get(r.LinkObjectId) || null;
        }
      }
    } catch (ex) {
      console.error('[NotificationHelper] ShapePage link lookup: ' + ex.message);
    }
    return rows.map(this.Shape);
  };

  /** The columns Shape reads, so a findAll does not select the whole row. */
  ShapeAttributes = [
    'Id',
    'Notes',
    'NotesMn',
    'Action',
    'LinkObjectName',
    'LinkObjectId',
    'Url',
    'Seen',
    'SeenDate',
    'CreateDate',
  ];

  /**
   * Persist a notification and, optionally, push it in real time.
   *
   * Signature unchanged - AdviceController calls this in three places. What
   * changed is that a Data carrying ToPatientId is no longer ignored.
   */
  SaveNotification = async function ({ Data, LogedUser, SendNotification }) {
    try {
      if (!Data || !LogedUser) return null;
      if (!Data.ToUserId && !Data.ToPatientId && !Data.ToDoctorId) {
        // Nobody to tell. Worth a line, because the old code reached this state
        // constantly and said nothing.
        console.error('[NotificationHelper] no recipient on notification, dropped');
        return null;
      }

      const Row = Object.assign({}, Data, {
        CreateDate: Data.CreateDate || ObjectHelper.getDateYMDHMS(),
        CreateUserId: Data.CreateUserId || LogedUser.Id || null,
      });

      const created = await Models.Notification.create(Row);
      const NotificationId = created ? created.Id : null;
      if (!NotificationId) return null;

      if (SendNotification === true) {
        // Route by recipient. NotificationSocket already takes a UserType and
        // defaults it to 'S', so patients only needed to be passed one - no
        // socket change was required.
        if (Data.ToPatientId) {
          NotificationSocket.SendNotification({
            UserType: 'P',
            UserId: Data.ToPatientId,
            Data: NotificationId,
          });
        }
        if (Data.ToUserId) {
          NotificationSocket.SendNotification({
            UserType: 'S',
            UserId: Data.ToUserId,
            Data: NotificationId,
          });
        }
      }

      return NotificationId;
    } catch (ex) {
      console.error('[NotificationHelper] SaveNotification: ' + ex.message);
      return null;
    }
  };

  /**
   * The wrapper producers call to tell a patient something.
   *
   * Writes the bell row, emits over the socket for an app that is open, and
   * makes one best-effort push attempt for one that is not. The push is awaited
   * so its failure is logged against this request, but PushHelper never throws
   * and its result is never checked - a silent phone must not fail the clinical
   * action that triggered it.
   */
  NotifyPatient = async function ({
    PatientId,
    Notes,
    NotesMn,
    Action,
    LinkObjectName,
    LinkObjectId,
    Url,
    ExpiredDate,
    LogedUser,
    Push,
    // The deep link's parent ticket, for the push payload - see ShapePage.
    // patientId in the payload is the recipient: a patient's links are theirs.
    AdviceId,
  }) {
    if (!PatientId) return null;

    const Id = await this.SaveNotification({
      Data: {
        ToPatientId: PatientId,
        Notes: Notes || null,
        NotesMn: NotesMn || null,
        Action: Action || null,
        LinkObjectName: LinkObjectName || null,
        LinkObjectId: LinkObjectId || null,
        Url: Url || null,
        ExpiredDate: ExpiredDate || null,
      },
      LogedUser: LogedUser || {},
      SendNotification: true,
    });

    if (Id && Push !== false) {
      await PushHelper.Send({
        UserType: 'P',
        UserId: PatientId,
        Title: 'MnCardio',
        // The Mongolian text is what the patient reads; Notes is the English
        // developer-facing label and is not shown to anyone.
        Body: NotesMn || Notes || '',
        Data: {
          notificationId: Id,
          linkObjectName: LinkObjectName || '',
          linkObjectId: LinkObjectId || '',
          patientId: String(PatientId || ''),
          adviceId: String(AdviceId || ''),
          action: Action || '',
        },
      });
    }

    return Id;
  };

  /** The staff equivalent, so producers do not hand-build a Data object. */
  NotifyUser = async function ({
    UserId,
    Notes,
    NotesMn,
    Action,
    LinkObjectName,
    LinkObjectId,
    Url,
    LogedUser,
    Push,
    // The deep link's parent, for the push payload - see ShapePage.
    PatientId,
    AdviceId,
  }) {
    if (!UserId) return null;

    const Id = await this.SaveNotification({
      Data: {
        ToUserId: UserId,
        Notes: Notes || null,
        NotesMn: NotesMn || null,
        Action: Action || null,
        LinkObjectName: LinkObjectName || null,
        LinkObjectId: LinkObjectId || null,
        Url: Url || null,
      },
      LogedUser: LogedUser || {},
      SendNotification: true,
    });

    if (Id && Push !== false) {
      await PushHelper.Send({
        UserType: 'S',
        UserId,
        Title: 'MnCardio',
        Body: NotesMn || Notes || '',
        Data: {
          notificationId: Id,
          linkObjectName: LinkObjectName || '',
          linkObjectId: LinkObjectId || '',
          patientId: String(PatientId || ''),
          adviceId: String(AdviceId || ''),
          action: Action || '',
        },
      });
    }

    return Id;
  };
}

module.exports = new NotificationHelper();
