const Sequelize = require('sequelize');
const sequelize = require('../../config/DbConnection');

Sequelize.DATE.prototype._stringify = function _stringify(date, options) {
  return this._applyTimezone(date, options).format('YYYY-MM-DD HH:mm:ss.SSS');
};

class Icd extends Sequelize.Model {}
Icd.init(
  {
    id: { type: Sequelize.BIGINT, primaryKey: true, autoIncrement: true },
    patientRegister: { type: Sequelize.STRING, allowNull: false },

    col1: { type: Sequelize.STRING },
    col2: { type: Sequelize.DATEONLY },
    col3: { type: Sequelize.STRING },
    col4: { type: Sequelize.STRING },
    col5: { type: Sequelize.DATEONLY },
    col6: { type: Sequelize.STRING },
    col7: { type: Sequelize.DATEONLY },
    col8: { type: Sequelize.STRING },
    col9: { type: Sequelize.STRING },
    col10: { type: Sequelize.STRING },
    col11: { type: Sequelize.STRING },
    col12: { type: Sequelize.STRING },
    col13: { type: Sequelize.STRING },
    col14: { type: Sequelize.STRING },
    col15: { type: Sequelize.STRING },
    col16: { type: Sequelize.STRING },
    col17: { type: Sequelize.STRING },
    col18: { type: Sequelize.STRING },
    col19: { type: Sequelize.STRING },
    col20: { type: Sequelize.STRING },
    col21: { type: Sequelize.STRING },
    col22: { type: Sequelize.STRING },
    col23: { type: Sequelize.STRING },
    col24: { type: Sequelize.STRING },
    col25: { type: Sequelize.STRING },
    col26: { type: Sequelize.STRING },
    col27: { type: Sequelize.STRING },
    col28: { type: Sequelize.STRING },
    col29: { type: Sequelize.STRING },
    col30: { type: Sequelize.STRING },
    col31: { type: Sequelize.STRING },
    col32: { type: Sequelize.STRING },
    col33: { type: Sequelize.STRING },
    col34: { type: Sequelize.DATEONLY },
    col35: { type: Sequelize.STRING },
    col36: { type: Sequelize.DATEONLY },
    col37: { type: Sequelize.STRING },
    col38: { type: Sequelize.STRING },
    col39: { type: Sequelize.STRING },
    col40: { type: Sequelize.STRING },
    col41: { type: Sequelize.STRING },
    col42: { type: Sequelize.STRING },
    col43: { type: Sequelize.STRING },
    col44: { type: Sequelize.STRING },
    col45: { type: Sequelize.STRING },
    col46: { type: Sequelize.STRING },
    col47: { type: Sequelize.STRING },
    col48: { type: Sequelize.STRING },
    col49: { type: Sequelize.STRING },
    col50: { type: Sequelize.STRING },
    col51: { type: Sequelize.STRING },
    col52: { type: Sequelize.STRING },
    col53: { type: Sequelize.STRING },
    col54: { type: Sequelize.STRING },
    col55: { type: Sequelize.STRING },
    col56: { type: Sequelize.STRING },
    col57: { type: Sequelize.STRING },
    col58: { type: Sequelize.STRING },
    col59: { type: Sequelize.STRING },
    col60: { type: Sequelize.STRING },
    col61: { type: Sequelize.STRING },
    col62: { type: Sequelize.STRING },
    col63: { type: Sequelize.STRING },
    col64: { type: Sequelize.STRING },
    col65: { type: Sequelize.STRING },
    col66: { type: Sequelize.STRING },
    col67: { type: Sequelize.STRING },
    col68: { type: Sequelize.STRING },
    col69: { type: Sequelize.STRING },
    col70: { type: Sequelize.STRING },
    col71: { type: Sequelize.STRING },
    col72: { type: Sequelize.STRING },
    col73: { type: Sequelize.STRING },
    col74: { type: Sequelize.STRING },
    col75: { type: Sequelize.STRING },
    col76: { type: Sequelize.STRING },
    col77: { type: Sequelize.STRING },
    col78: { type: Sequelize.STRING },
    col79: { type: Sequelize.STRING },
    col80: { type: Sequelize.STRING },
    col81: { type: Sequelize.STRING },
    col82: { type: Sequelize.STRING },
    col83: { type: Sequelize.STRING },
    col84: { type: Sequelize.STRING },
    col85: { type: Sequelize.STRING },
    col86: { type: Sequelize.STRING },
    col87: { type: Sequelize.STRING },
    col88: { type: Sequelize.STRING },
    col89: { type: Sequelize.STRING },
    col90: { type: Sequelize.STRING },
    col91: { type: Sequelize.STRING },
    col92: { type: Sequelize.DATEONLY },
    col93: { type: Sequelize.DATEONLY },
    col94: { type: Sequelize.STRING },
    col95: { type: Sequelize.STRING },
    col96: { type: Sequelize.STRING },
    col97: { type: Sequelize.STRING },
    col98: { type: Sequelize.STRING },
    col99: { type: Sequelize.STRING },
    col100: { type: Sequelize.STRING },
    col101: { type: Sequelize.STRING },
    col102: { type: Sequelize.STRING },
    col103: { type: Sequelize.STRING },
    col104: { type: Sequelize.DATEONLY },
    col105: { type: Sequelize.STRING },
    col106: { type: Sequelize.STRING },
    col107: { type: Sequelize.STRING },
    col108: { type: Sequelize.STRING },
    col109: { type: Sequelize.STRING },
    col110: { type: Sequelize.STRING },
    col111: { type: Sequelize.STRING },
    col112: { type: Sequelize.STRING },

    CreateDate: { type: Sequelize.DATE },
    CreateUserId: { type: Sequelize.INTEGER },
  },
  {
    sequelize,
    tableName: 'Icd',
    modelName: 'Icd',
    timestamps: false,
  }
);

Icd.SetAssocations = (Models) => {
  Icd.belongsTo(Models.DoctorsProfile, {
    as: 'DoctorsProfile',
    foreignKey: 'createUserId',
    targetKey: 'UserId',
  });
  // Icd.belongsTo(Models.Organization, {
  //   as: "Organization",
  //   foreignKey: "organization_id",
  //   targetKey: "id",
  // });
};

module.exports = Icd;
