const Sequelize = require('sequelize');
const sequelize = require('../../config/DbConnection');
const Op = Sequelize.Op;

Sequelize.DATE.prototype._stringify = function _stringify(date, options) {
  return this._applyTimezone(date, options).format('YYYY-MM-DD HH:mm:ss.SSS');
};

class FollowUp extends Sequelize.Model {}
FollowUp.init(
  {
    id_data: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
    id: { type: Sequelize.INTEGER },

    id_group: { type: Sequelize.INTEGER },
    date_creation: { type: Sequelize.DATE },
    user_mod: { type: Sequelize.STRING },
    date_modif: { type: Sequelize.DATE },

    rec_status: { type: Sequelize.INTEGER },
    fu_hosp_date: { type: Sequelize.DATE },
    fu_pe_severity: { type: Sequelize.STRING },
    fu_pe_vs_heart: { type: Sequelize.INTEGER },
    fu_pe_heent: { type: Sequelize.STRING },
    fu_pe_skin: { type: Sequelize.STRING },
    fu_pe_muscle: { type: Sequelize.STRING },
    fu_pe_joints: { type: Sequelize.STRING },
    fu_pe_resp_sys: { type: Sequelize.STRING },
    fu_pe_circ_sys: { type: Sequelize.STRING },
    fu_pe_gast_sys: { type: Sequelize.STRING },
    fu_pe_nephrology: { type: Sequelize.STRING },
    fu_pe_other: { type: Sequelize.STRING },
    fu_cbc_w_blood: { type: Sequelize.STRING },
    fu_cbc_r_blood: { type: Sequelize.STRING },
    fu_cbc_hemoglobin: { type: Sequelize.STRING },
    fu_cbc_hematocrit: { type: Sequelize.STRING },
    fu_cbc_platelet: { type: Sequelize.STRING },
    fu_cbc_esr: { type: Sequelize.STRING },
    fu_cbc_other: { type: Sequelize.STRING },
    fu_bio_protein: { type: Sequelize.STRING },
    fu_bio_albumin: { type: Sequelize.STRING },
    fu_bio_creatinine: { type: Sequelize.STRING },
    fu_bio_mochevin: { type: Sequelize.STRING },
    fu_bio_uldegdel: { type: Sequelize.STRING },
    fu_bio_got: { type: Sequelize.STRING },
    fu_bio_gpt: { type: Sequelize.STRING },
    fu_bio_amilase: { type: Sequelize.STRING },
    fu_bio_sugar: { type: Sequelize.STRING },
    fu_bio_cholesterol: { type: Sequelize.STRING },
    fu_bio_sodium: { type: Sequelize.STRING },
    fu_bio_potassium: { type: Sequelize.STRING },
    fu_bio_ldg: { type: Sequelize.STRING },
    fu_bio_other: { type: Sequelize.STRING },
    fu_urine_volume: { type: Sequelize.STRING },
    fu_urine_color: { type: Sequelize.STRING },
    fu_urine_bulingar: { type: Sequelize.STRING },
    fu_urine_r_blood: { type: Sequelize.STRING },
    fu_urine_w_blood: { type: Sequelize.STRING },
    fu_urine_rbc_micr: { type: Sequelize.STRING },
    fu_urine_wbc_micr: { type: Sequelize.STRING },
    fu_urine_bilirubin: { type: Sequelize.STRING },
    fu_urine_urobilinogen: { type: Sequelize.STRING },
    fu_urine_khuviin: { type: Sequelize.STRING },
    fu_urine_ketonii: { type: Sequelize.STRING },
    fu_urine_protein: { type: Sequelize.STRING },
    fu_urine_nitrit: { type: Sequelize.STRING },
    fu_urine_sugar: { type: Sequelize.STRING },
    fu_urine_ph: { type: Sequelize.STRING },
    fu_urine_other: { type: Sequelize.STRING },
    fu_echo_concl: { type: Sequelize.STRING },
    fu_ecg_concl: { type: Sequelize.STRING },
    fu_other_xray: { type: Sequelize.STRING },
    fu_other_abdo: { type: Sequelize.STRING },
    fu_other_other: { type: Sequelize.STRING },
    fu_c_comp: { type: Sequelize.STRING },
    fu_history_ill: { type: Sequelize.STRING },
    fu_m_diag: { type: Sequelize.STRING },
    fu_c_diag: { type: Sequelize.STRING },
    fu_s_bp: { type: Sequelize.INTEGER },
    fu_d_bp: { type: Sequelize.INTEGER },
    fu_resp: { type: Sequelize.INTEGER },
    fu_temp: { type: Sequelize.STRING },
    heent_ab: { type: Sequelize.STRING },
    skin_ab: { type: Sequelize.STRING },
    muscle_ab: { type: Sequelize.STRING },
    joints_ab: { type: Sequelize.STRING },
    res_ab: { type: Sequelize.STRING },
    cir_ab: { type: Sequelize.STRING },
    gas_ab: { type: Sequelize.STRING },
    neph_ab: { type: Sequelize.STRING },
    oth_ab: { type: Sequelize.STRING },
    other1: { type: Sequelize.STRING },
    other2: { type: Sequelize.STRING },
    other3: { type: Sequelize.STRING },
    other4: { type: Sequelize.STRING },
    cbcyorn: { type: Sequelize.STRING },
    biochemyorn: { type: Sequelize.STRING },
    urineyorn: { type: Sequelize.STRING },
    olabyorn1: { type: Sequelize.STRING },
    olabyorn2: { type: Sequelize.STRING },
    olabyorn3: { type: Sequelize.STRING },
    olabyorn4: { type: Sequelize.STRING },
    ultrasoundyorn: { type: Sequelize.STRING },
    ecgyorn: { type: Sequelize.STRING },
    otherimagesyorn: { type: Sequelize.STRING },
    fu_c_comp_code: { type: Sequelize.STRING },
    stroke_chief_complaint: { type: Sequelize.STRING },
    fu_m_diag_code: { type: Sequelize.STRING },
    fu_c_diag_code: { type: Sequelize.STRING },
    fu_pe_circ_sys_code: { type: Sequelize.STRING },
    fu_pe_gast_sys_code: { type: Sequelize.STRING },
    fu_pe_joint_code: { type: Sequelize.STRING },
    fu_pe_muscle_code: { type: Sequelize.STRING },
    fu_pe_nephrology_code: { type: Sequelize.STRING },
    fu_pe_resp_sys_code: { type: Sequelize.STRING },
    fu_pe_skin_code: { type: Sequelize.STRING },
    fu_pe_circ_sys_loc_code: { type: Sequelize.STRING },
    fu_pe_vs_urine: { type: Sequelize.INTEGER },
    fu_pe_loc_ao: { type: Sequelize.STRING },
    fu_pe_loc_mv: { type: Sequelize.STRING },
    fu_pe_loc_pv: { type: Sequelize.STRING },
    fu_pe_loc_tv: { type: Sequelize.STRING },
    fu_pe_circ_sys_code1: { type: Sequelize.STRING },
    fu_pe_circ_sys_code2: { type: Sequelize.STRING },
    fu_pe_circ_sys_code3: { type: Sequelize.STRING },
    fu_pe_resp_sys_code1: { type: Sequelize.STRING },
    fu_pe_resp_rlung: { type: Sequelize.STRING },
    fu_pe_resp_llung: { type: Sequelize.STRING },
    fu_vs_bodyweight: { type: Sequelize.STRING },
    fu_vs_height: { type: Sequelize.INTEGER },
    amis_qstnr: { type: Sequelize.STRING },
    amis_p_a_dob: { type: Sequelize.DATE },
    amis_p_a_gender: { type: Sequelize.STRING },
    amis_p_a_heart_rhythm: { type: Sequelize.STRING },
    amis_p_a_heart_rhythm_other: { type: Sequelize.STRING },
    AdviceId: { type: Sequelize.INTEGER },
  },
  {
    sequelize,
    tableName: 'FollowUp',
    modelName: 'FollowUp',
    timestamps: false,
  }
);
FollowUp.SearchField = [
  'id_data',
  'id',
  'id_group',
  'date_creation',
  'user_mod',
  'date_modif',
  'rec_status',
  'fu_hosp_date',
  'fu_pe_severity',
  'fu_pe_vs_heart',
  'fu_pe_heent',
  'fu_pe_skin',
  'fu_pe_muscle',
  'fu_pe_joints',
  'fu_pe_resp_sys',
  'fu_pe_circ_sys',
  'fu_pe_gast_sys',
  'fu_pe_nephrology',
  'fu_pe_other',
  'fu_cbc_w_blood',
  'fu_cbc_r_blood',
  'fu_cbc_hemoglobin',
  'fu_cbc_hematocrit',
  'fu_cbc_platelet',
  'fu_cbc_esr',
  'fu_cbc_other',
  'fu_bio_protein',
  'fu_bio_albumin',
  'fu_bio_creatinine',
  'fu_bio_mochevin',
  'fu_bio_uldegdel',
  'fu_bio_got',
  'fu_bio_gpt',
  'fu_bio_amilase',
  'fu_bio_sugar',
  'fu_bio_cholesterol',
  'fu_bio_sodium',
  'fu_bio_potassium',
  'fu_bio_ldg',
  'fu_bio_other',
  'fu_urine_volume',
  'fu_urine_color',
  'fu_urine_bulingar',
  'fu_urine_r_blood',
  'fu_urine_w_blood',
  'fu_urine_rbc_micr',
  'fu_urine_wbc_micr',
  'fu_urine_bilirubin',
  'fu_urine_urobilinogen',
  'fu_urine_khuviin',
  'fu_urine_ketonii',
  'fu_urine_protein',
  'fu_urine_nitrit',
  'fu_urine_sugar',
  'fu_urine_ph',
  'fu_urine_other',
  'fu_echo_concl',
  'fu_ecg_concl',
  'fu_other_xray',
  'fu_other_abdo',
  'fu_other_other',
  'fu_c_comp',
  'fu_history_ill',
  'fu_m_diag',
  'fu_c_diag',
  'fu_s_bp',
  'fu_d_bp',
  'fu_resp',
  'fu_temp',
  'heent_ab',
  'skin_ab',
  'muscle_ab',
  'joints_ab',
  'res_ab',
  'cir_ab',
  'gas_ab',
  'neph_ab',
  'oth_ab',
  'other1',
  'other2',
  'other3',
  'other4',
  'cbcyorn',
  'biochemyorn',
  'urineyorn',
  'olabyorn1',
  'olabyorn2',
  'olabyorn3',
  'olabyorn4',
  'ultrasoundyorn',
  'ecgyorn',
  'otherimagesyorn',
  'fu_c_comp_code',
  'fu_m_diag_code',
  'fu_c_diag_code',
  'fu_pe_circ_sys_code',
  'fu_pe_gast_sys_code',
  'fu_pe_joint_code',
  'fu_pe_muscle_code',
  'fu_pe_nephrology_code',
  'fu_pe_resp_sys_code',
  'fu_pe_skin_code',
  'fu_pe_circ_sys_loc_code',
  'fu_pe_vs_urine',
  'fu_pe_loc_ao',
  'fu_pe_loc_mv',
  'fu_pe_loc_pv',
  'fu_pe_loc_tv',
  'fu_pe_circ_sys_code1',
  'fu_pe_circ_sys_code2',
  'fu_pe_circ_sys_code3',
  'fu_pe_resp_sys_code1',
  'fu_pe_resp_rlung',
  'fu_pe_resp_llung',
  'fu_vs_bodyweight',
  'fu_vs_height',
  'amis_qstnr',
  'amis_p_a_dob',
  'amis_p_a_gender',
  'amis_p_a_heart_rhythm',
  'amis_p_a_heart_rhythm_other',
];

FollowUp.SetAssocations = (Models) => {
  FollowUp.hasMany(Models.FollowUpLookUp, {
    as: 'LookUpData',
    foreignKey: 'id_data',
  });

  FollowUp.belongsTo(Models.Advice, {
    as: 'Advice',
    foreignKey: 'AdviceId',
    targetKey: 'id_data',
  });
};

FollowUp.SetFunctions = (Models) => {
  FollowUp.GetFiles = async function (id_data) {
    const Files = await Models.File.findAll({
      where: {
        LinkedObjectId: id_data,
        LinkedObjectName: 'FollowUp',
        rec_status: { [Op.in]: ['9', '1'] },
      },
      attributes: [
        'id_data',
        'id',
        'ext',
        'hash',
        'original_name',
        'generated_name',
        'linked_q',
        'linked_id_data',
        'size',
        'patient_id',
        'LinkedObjectName',
        'LinkedObjectId',
        'FieldName',
      ],
    });
    return Files;
  };

  FollowUp.GetLookUpData = async function (DataId) {
    const result = await Models.FollowUpLookUp.findAll({
      where: { id_data: DataId },
    });
    return result;
  };

  FollowUp.createNew = async function (Data, ReturnIdField) {
    await FollowUp.create(Data);
    const [ReturnData] = await sequelize.query(
      'SELECT TOP 1  ' + ReturnIdField + ' FROM [FollowUp] ORDER BY ' + ReturnIdField + ' DESC '
    );
    return ReturnData[0][ReturnIdField];
  };

  FollowUp.findAllDetail = async function (Option) {
    const result = await FollowUp.findAll({
      ...Option,
      include: [{ model: Models.FollowUpLookUp, as: 'LookUpData' }],
    });
    return result;
  };
};

module.exports = FollowUp;
