const { Models } = require('../config/DB');
const Model = Models.CardiacSurgeryReport;
var ModelLookUp = Models.CardiacSurgeryReportLookUp;

function CardiacSurgeryReportConfig() {
  this.Fields = [
    [
      {
        Name: 'PatientId',
        Label: 'Patient ID',
        Type: 'GridLookUpSingleLoad',
        Config: {
          ObjectName: 'Patient',
          IdField: 'id_data',
          TextField: 'p_registration',
          Fields: [
            // { Name: "id_data", Label: "Id" },
            { Name: 'p_lastname', Label: 'Last name' },
            { Name: 'p_firstname', Label: 'first name' },
            { Name: 'p_registration', Label: 'Register' },
            { Name: 'DictProvinceCity.name', Label: 'City' },
          ],
          MinTextLength: '2',
        },
        EditField: false,
        GridField: false,
      },
      {
        Name: 'DoctorsProfile.FullName',
        Label: 'Doctor',
        Type: 'Text',
        EditField: false,
      },
      {
        Name: 'OrganizationId',
        Label: 'OrganizationId',
        Type: 'Text',
        GridField: false,
      },
      {
        Name: 'Organization.Name',
        Label: 'Organization',
        Type: 'Text',
        EditField: false,
      },
      {
        Name: 'Patient.p_lastname',
        Type: 'Text',
        Label: 'Last name',
        GridField: false,
      },
      { Name: 'Patient.p_firstname', Type: 'Text', Label: 'First name' },
      { Name: 'Patient.p_registration', Type: 'Text', Label: 'Register' },
      { Name: 'Patient.p_birthday', Type: 'Text', Label: 'Birth date' },
      { Name: 'Patient.Age', Type: 'Text', Label: 'Age' },
      {
        Name: 'date_creation',
        Label: 'Creation date',
        Type: 'Date',
        EditField: false,
      },

      {
        Name: 'OrganizationId',
        Type: 'Text',
        Label: 'Organization',
        EditField: false,
        GridField: false,
      },

      {
        Name: 'angina',
        Label: 'Angina (CCS class)',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_angina',
        EditField: false,
        GridField: false,
        Position: 1,
      },
      {
        Name: 'aortic_proc',
        Label: 'Aortic procedure',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_aor_proc',
        EditField: false,
        GridField: false,
        Position: 2,
      },
      {
        Name: 'art_used_grafts',
        Label: 'Artery / Arteries used as grafts',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_art_use_graf',
        EditField: false,
        GridField: false,
        Position: 3,
      },
      {
        Name: 'av_gradient',
        Label: 'AV gradient',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 4,
      },
      {
        Name: 'bypass_time',
        Label: 'Bypass time',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 5,
      },
      {
        Name: 'cardio_shock',
        Label: 'Cardiogenic shock',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 6,
      },
      {
        Name: 'cardiopulmonary_bypass',
        Label: 'Cardiopulmonary bypass',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_carpul_bypas',
        EditField: false,
        GridField: false,
        Position: 7,
      },
      {
        Name: 'carotid_bruits',
        Label: 'Carotid bruits',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 8,
      },
      {
        Name: 'cerebvas_disease_type',
        Label: 'Cerebrovascular disease type',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_cerebvas_dis',
        EditField: false,
        GridField: false,
        Position: 9,
      },
      {
        Name: 'chr_lung_disease',
        Label: 'Chronic lung disease',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_lung_disease',
        EditField: false,
        GridField: false,
        Position: 10,
      },
      {
        Name: 'congestive_heart_failure',
        Label: 'Congestive heart failure',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 11,
      },
      {
        Name: 'cumulative_cross_clamp_time',
        Label: 'Cumulative cross-clamp time',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 12,
      },
      {
        Name: 'date_last_cath',
        Label: 'Date of last catheterisation',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 14,
      },
      {
        Name: 'date_last_pci',
        Label: 'Date of last PCI',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 15,
      },
      {
        Name: 'date_last_sur',
        Label: 'Date of last cardiac surgery',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 16,
      },
      {
        Name: 'date_modif',
        Label: 'Update date',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 17,
      },
      {
        Name: 'date_of_admission',
        Label: 'Date-of-admission',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 18,
      },
      {
        Name: 'date_of_discharge_death',
        Label: 'Date-of-discharge / Date-of-death',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 19,
      },
      {
        Name: 'date_of_operation',
        Label: 'Date-of-operation',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 20,
      },
      {
        Name: 'dca_art_conduit',
        Label: 'DCAs - arterial conduits',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 21,
      },
      {
        Name: 'dca_ven_conduit',
        Label: 'DCAs - venous conduits',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 22,
      },
      {
        Name: 'destination_on_discharge',
        Label: 'Destination on discharge',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_destdischarg',
        EditField: false,
        GridField: false,
        Position: 23,
      },
      {
        Name: 'diab_treatment',
        Label: 'Diabetes treatment',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_diab_treat',
        EditField: false,
        GridField: false,
        Position: 24,
      },
      {
        Name: 'dyspnoea',
        Label: 'Dyspnoea (NYHA grade)',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_dyspnoea',
        EditField: false,
        GridField: false,
        Position: 25,
      },
      {
        Name: 'ef_category',
        Label: 'Ejection fraction category',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_efcategory',
        EditField: false,
        GridField: false,
        Position: 26,
      },
      {
        Name: 'ef_value',
        Label: 'Ejection fraction value',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 27,
      },
      {
        Name: 'explant_type_av',
        Label: 'Explant type AV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_explanttype',
        EditField: false,
        GridField: false,
        Position: 28,
      },
      {
        Name: 'explant_type_mv',
        Label: 'Explant type MV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_explanttype',
        EditField: false,
        GridField: false,
        Position: 29,
      },
      {
        Name: 'explant_type_pv',
        Label: 'Explant type PV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_explanttype',
        EditField: false,
        GridField: false,
        Position: 30,
      },
      {
        Name: 'explant_type_tv',
        Label: 'Explant type TV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_explanttype',
        EditField: false,
        GridField: false,
        Position: 31,
      },
      {
        Name: 'ext_card_arteriopathy',
        Label: 'Extra-cardiac arteriopathy',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_ecardiac_art',
        EditField: false,
        GridField: false,
        Position: 32,
      },
      {
        Name: 'height',
        Label: 'Height',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 33,
      },
      {
        Name: 'hypercholesterolaemia',
        Label: 'Hypercholesterolaemia',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 34,
      },
      {
        Name: 'hypertension',
        Label: 'Hypertension',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_hypertension',
        EditField: false,
        GridField: false,
        Position: 35,
      },
      {
        Name: 'id',
        Label: 'User ID',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 36,
      },
      {
        Name: 'id_data',
        Label: 'Record ID',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 37,
      },
      {
        Name: 'id_group',
        Label: 'Group',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 38,
      },
      {
        Name: 'implant_code_av',
        Label: 'Implant code AV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 40,
      },
      {
        Name: 'implant_code_mv',
        Label: 'Implant code MV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 41,
      },
      {
        Name: 'implant_code_pv',
        Label: 'Implant code PV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 42,
      },
      {
        Name: 'implant_code_tv',
        Label: 'Implant code TV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 43,
      },
      {
        Name: 'implant_type_av',
        Label: 'Implant type AV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_imptype_av',
        EditField: false,
        GridField: false,
        Position: 44,
      },
      {
        Name: 'implant_type_mv',
        Label: 'Implant type MV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_imptype_mvtv',
        EditField: false,
        GridField: false,
        Position: 45,
      },
      {
        Name: 'implant_type_pv',
        Label: 'Implant type PV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_imptype_pv',
        EditField: false,
        GridField: false,
        Position: 46,
      },
      {
        Name: 'implant_type_tv',
        Label: 'Implant type TV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_imptype_mvtv',
        EditField: false,
        GridField: false,
        Position: 47,
      },
      {
        Name: 'insufficiency_av',
        Label: 'Insufficiency AV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_insufficienc',
        EditField: false,
        GridField: false,
        Position: 48,
      },
      {
        Name: 'insufficiency_mv',
        Label: 'Insufficiency MV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_insufficienc',
        EditField: false,
        GridField: false,
        Position: 49,
      },
      {
        Name: 'insufficiency_pv',
        Label: 'Insufficiency PV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_insufficienc',
        EditField: false,
        GridField: false,
        Position: 50,
      },
      {
        Name: 'insufficiency_tv',
        Label: 'Insufficiency TV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_insufficienc',
        EditField: false,
        GridField: false,
        Position: 51,
      },
      {
        Name: 'iv_inotropes',
        Label: 'IV inotropes',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 52,
      },
      {
        Name: 'iv_nit_hep_any_kind',
        Label: 'IV nitrates / heparin of any kind',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 53,
      },
      {
        Name: 'last_preo_creatine',
        Label: 'Last pre-operative creatinine',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 54,
      },
      {
        Name: 'left_right_heart_cath',
        Label: 'Left- or right-heart catheterisation',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_lrhcath',
        EditField: false,
        GridField: false,
        Position: 55,
      },
      {
        Name: 'lms_disease',
        Label: 'Left main stem disease',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_lmstemdiseas',
        EditField: false,
        GridField: false,
        Position: 56,
      },
      {
        Name: 'lvedp',
        Label: 'LVEDP',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 58,
      },
      {
        Name: 'mean_pawp_la',
        Label: 'Mean PAWP / LA',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 59,
      },
      {
        Name: 'most_rcnt_myo_infarction',
        Label: 'Most recent myocardial infarction',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_mrmi',
        EditField: false,
        GridField: false,
        Position: 60,
      },
      {
        Name: 'multi_system_failure',
        Label: 'Multi-system failure',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 61,
      },
      {
        Name: 'nat_val_path_av',
        Label: 'Native valve pathology AV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 62,
      },
      {
        Name: 'nat_val_path_mv',
        Label: 'Native valve pathology MV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 63,
      },
      {
        Name: 'nat_val_path_pv',
        Label: 'Native valve pathology PV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 64,
      },
      {
        Name: 'nat_val_path_tv',
        Label: 'Native valve pathology TV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 65,
      },
      {
        Name: 'nb_dis_cor_vess',
        Label: 'Number of diseased coronary vessels',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_nbdcv',
        EditField: false,
        GridField: false,
        Position: 66,
      },
      {
        Name: 'nb_prev_myo_infarction',
        Label: 'Number of previous myocardial infarctions',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_nbprevinfarc',
        EditField: false,
        GridField: false,
        Position: 67,
      },
      {
        Name: 'neuro_dysfunction',
        Label: 'Neurological dysfunction',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 68,
      },
      {
        Name: 'new_post_operative_dialysis',
        Label: 'New post-operative dialysis',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 69,
      },
      {
        Name: 'new_post_operative_stroke',
        Label: 'New post-operative stroke',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_newpostopstr',
        EditField: false,
        GridField: false,
        Position: 70,
      },
      {
        Name: 'oth_car_proc_det',
        Label: 'Other cardiac procedures detail',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_othcar_surg',
        EditField: false,
        GridField: false,
        Position: 71,
      },
      {
        Name: 'oth_non_car_proc_det',
        Label: 'Other non-cardiac procedures detail',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_othnoncarpro',
        EditField: false,
        GridField: false,
        Position: 72,
      },
      {
        Name: 'pa_systolic',
        Label: 'PA systolic',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 73,
      },
      {
        Name: 'patient_status_discharge',
        Label: 'Patient status at discharge',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_patstatdisch',
        EditField: false,
        GridField: false,
        Position: 74,
      },
      {
        Name: 'preo_heart_rhythm',
        Label: 'Pre-operative heart rhythm',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_preo_hrt_rhy',
        EditField: false,
        GridField: false,
        Position: 75,
      },
      {
        Name: 'prev_pci',
        Label: 'Previous PCI',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_prev_pci',
        EditField: false,
        GridField: false,
        Position: 76,
      },
      {
        Name: 'prev_surgery',
        Label: 'Previous cardiac, vascular or thoracic surgery',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_prev_sur',
        EditField: false,
        GridField: false,
        Position: 77,
      },
      {
        Name: 'primary_cause_death',
        Label: 'Primary cause of death',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_pricausdeath',
        EditField: false,
        GridField: false,
        Position: 78,
      },
      {
        Name: 'procedure_group',
        Label: 'Procedure group',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_proc_group',
        EditField: false,
        GridField: false,
        Position: 79,
      },
      {
        Name: 're_operation',
        Label: 'Re-operation',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_reoperation',
        EditField: false,
        GridField: false,
        Position: 80,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'rec_status',
        EditField: false,
        GridField: false,
        Position: 81,
      },
      {
        Name: 'renal',
        Label: 'Renal',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_renal',
        EditField: false,
        GridField: false,
        Position: 83,
      },
      {
        Name: 'rsn_rpt_vlv_sur_av',
        Label: 'Reason for repeat valve surgery AV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_reasnrepsurg',
        EditField: false,
        GridField: false,
        Position: 84,
      },
      {
        Name: 'rsn_rpt_vlv_sur_mv',
        Label: 'Reason for repeat valve surgery MV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_reasnrepsurg',
        EditField: false,
        GridField: false,
        Position: 85,
      },
      {
        Name: 'rsn_rpt_vlv_sur_pv',
        Label: 'Reason for repeat valve surgery PV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_reasnrepsurg',
        EditField: false,
        GridField: false,
        Position: 86,
      },
      {
        Name: 'rsn_rpt_vlv_sur_tv',
        Label: 'Reason for repeat valve surgery TV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_reasnrepsurg',
        EditField: false,
        GridField: false,
        Position: 87,
      },
      {
        Name: 'seg_aorta',
        Label: 'Segments of the aorta',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'sur_rep_seg_aorta',
        EditField: false,
        GridField: false,
        Position: 88,
      },
      {
        Name: 'smoking_history',
        Label: 'Smoking history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_smok_hist',
        EditField: false,
        GridField: false,
        Position: 89,
      },
      {
        Name: 'stenosis_av',
        Label: 'Stenosis AV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 90,
      },
      {
        Name: 'stenosis_mv',
        Label: 'Stenosis MV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 91,
      },
      {
        Name: 'stenosis_pv',
        Label: 'Stenosis PV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 92,
      },
      {
        Name: 'stenosis_tv',
        Label: 'Stenosis TV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 93,
      },
      {
        Name: 'total_circulatory_arrest_time',
        Label: 'Total circulatory arrest time',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 94,
      },
      {
        Name: 'user_mod',
        Label: 'Last update author',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 95,
      },
      {
        Name: 'valve_proc_av',
        Label: 'Valve procedure AV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_valveproc',
        EditField: false,
        GridField: false,
        Position: 96,
      },
      {
        Name: 'valve_proc_mv',
        Label: 'Valve procedure MV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_valveproc',
        EditField: false,
        GridField: false,
        Position: 97,
      },
      {
        Name: 'valve_proc_pv',
        Label: 'Valve procedure PV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_valveproc',
        EditField: false,
        GridField: false,
        Position: 98,
      },
      {
        Name: 'valve_proc_tv',
        Label: 'Valve procedure TV',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sur_rep_valveproc',
        EditField: false,
        GridField: false,
        Position: 99,
      },
      {
        Name: 'valve_ring_size_av',
        Label: 'Valve / ring size AV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 100,
      },
      {
        Name: 'valve_ring_size_mv',
        Label: 'Valve / ring size MV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 101,
      },
      {
        Name: 'valve_ring_size_pv',
        Label: 'Valve / ring size PV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 102,
      },
      {
        Name: 'valve_ring_size_tv',
        Label: 'Valve / ring size TV',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 103,
      },
      {
        Name: 'ventilated',
        Label: 'Ventilated',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 104,
      },
      {
        Name: 'weight',
        Label: 'Weight',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 105,
      },
    ],
  ];

  this.ObjectName = 'CardiacSurgeryReport';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Cardiac surgery report',
    NewObjectTitle: 'Cardiac surgery report create',
    EditObjectTitle: 'Cardiac surgery report edit',
  };
}

module.exports = CardiacSurgeryReportConfig;
