const { Models } = require('../config/DB');
const Model = Models.DoctorsProfile;

function DoctorsProfileConfig() {
  this.Fields = [
    [
      {
        Name: 'AppId',
        Label: 'App',
        Type: 'SingleSelect',
        Config: { Model: Models.Apps, TextField: 'Name', IdField: 'Id' },
        Position: 0,
        EditField: false,
        GridField: true,
      },
      { Label: 'Empty', md: 4, GridField: false },
      {
        Name: 'Files',
        Label: 'Profile image',
        Type: 'SingleImage',
        EditField: true,
        GridField: false,
      },
      { Label: 'Empty', md: 4, GridField: false },
    ],
    [
      {
        Name: 'personal_number',
        Label: 'Personal number',
        Type: 'Text',
        EditField: true,
        GridField: true,
      },
      {
        Name: 'telephone',
        Label: 'Telephone',
        Type: 'Text',
        EditField: true,
        GridField: true,
        Position: 1,
      },
      {
        Name: 'lastname',
        Label: 'Last name',
        Type: 'Text',
        EditField: true,
        GridField: true,
        Position: 2,
      },
      {
        Name: 'firstname',
        Label: 'First name',
        Type: 'Text',
        EditField: true,
        GridField: true,
        Position: 3,
      },
      {
        Name: 'Users.UserName',
        Label: 'User',
        Type: 'Text',
        Position: 4,
        EditField: false,
      },
      // {
      //   Name: "province_city",
      //   Label: "Province, City",
      //   Type: "SingleSelect",
      //   OptionType: "aimag",
      //   Config: { IdField: "Value", TextField: "Label" },
      //   EditField: false,
      //   GridField: false,
      //   Position: 4,
      // },
      // {
      //   Name: "addr_prov_city",
      //   Label: "Province/city",
      //   Type: "SingleSelect",
      //   Config: {
      //     Model: Models.DictProvinceCity,
      //     IdField: "id_data",
      //     TextField: "name",
      //     MinTextLength: 1,
      //   },
      //   GridField: false,
      //   EditField: true,
      //   Position: 5,
      // },
      // {
      //   Name: "ProvCityName",
      //   Label: "Province/city",
      //   Type: "Text",
      //   Position: 6,
      //   ReadOnly: true,
      //   GridField: false,
      //   EditField: false,
      // },
      // {
      //   Name: "addr_soum_dist",
      //   Label: "Soum/district",
      //   Type: "SingleSelect",
      //   Config: {
      //     SearchType: "AllData",
      //     Model: Models.DictSoumDistrict,
      //     ObjectName: "DictSoumDistrict",
      //     IdField: "id_data",
      //     TextField: "name",
      //     MinTextLength: 0,
      //     Fields: [
      //       { Name: "id_data", Label: "Id" },
      //       { Name: "name", Label: "Name" },
      //     ],
      //   },
      //   GridField: false,
      //   EditField: true,
      //   Position: 6,
      // },
      // {
      //   Name: "SoumDistName",
      //   Label: "Soum/district",
      //   Type: "Text",
      //   Position: 6,
      //   GridField: false,
      //   EditField: false,
      // },
      // {
      //   Name: "addr_bag_khoroo",
      //   Label: "Bag/khoroo",
      //   Type: "SingleSelect",
      //   GridField: false,
      //   EditField: true,
      //   Position: 7,
      //   Config: {
      //     SearchType: "AllData",
      //     Model: Models.DictBagKhoroo,
      //     ObjectName: "DictBagKhoroo",
      //     IdField: "id_data",
      //     TextField: "name",
      //     MinTextLength: 0,
      //     Fields: [
      //       { Name: "id_data", Label: "Id" },
      //       { Name: "name", Label: "Name" },
      //     ],
      //   },
      // },
      // {
      //   Name: "BagKhorooName",
      //   Label: "Bag/khoroo",
      //   Type: "Text",
      //   Position: 7,
      //   GridField: false,
      //   EditField: false,
      // },
      {
        Name: 'organisation',
        Label: 'Workplace',
        Type: 'Text',
        EditField: true,
        GridField: false,
        Position: 5,
      },
    ],
    [
      {
        Name: 'Organization.Name',
        Label: 'Organization',
        Type: 'Text',
        Position: 8,
        ReadOnly: true,
        GridField: true,
        EditField: false,
      },
      {
        Name: 'Organization.DictProvinceCity.name',
        Label: 'Province/city',
        Type: 'Text',
        Position: 8,
        ReadOnly: true,
        GridField: true,
        EditField: false,
      },
      {
        Name: 'Organization.DictSoumDistrict.name',
        Label: 'Soum/district',
        Type: 'Text',
        Position: 8,
        ReadOnly: true,
        GridField: true,
        EditField: false,
      },
      {
        Name: 'Organization.DictBagKhoroo.name',
        Label: 'Bag/khoroo',
        Type: 'Text',
        Position: 8,
        ReadOnly: true,
        GridField: true,
        EditField: false,
      },
    ],
    [
      {
        Name: 'is_editor',
        Label: 'Is an editor',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        EditField: false,
        GridField: false,
        Position: 9,
      },
    ],
    [
      {
        Name: 'position',
        Label: 'Position',
        Type: 'Text',
        EditField: true,
        GridField: true,
        Position: 10,
      },
      {
        Name: 'profession',
        Label: 'Profession',
        Type: 'Text',
        EditField: true,
        GridField: true,
        Position: 10,
      },
      {
        Name: 'email',
        Label: 'Email',
        Type: 'Text',
        EditField: true,
        GridField: true,
        Position: 12,
      },
    ],
    [
      {
        Name: 'skype',
        Label: 'Skype',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 13,
      },
      {
        Name: 'professional_degrees',
        Label: 'Professional degrees',
        Type: 'TextArea',
        EditField: true,
        GridField: true,
        Position: 14,
      },
      {
        Name: 'experiences',
        Label: 'Experiences',
        Type: 'TextArea',
        EditField: true,
        GridField: true,
        Position: 15,
      },
    ],
    //---------------------------------
    [
      {
        Name: 'date_modif',
        Label: 'Date de modification',
        Type: 'Date',
        EditField: false,
        GridField: false,
        Position: 16,
      },
      {
        Name: 'dr_group_id',
        Label: 'Group record ID',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 17,
      },
      {
        Name: 'dr_group_type',
        Label: 'Group table type',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 18,
      },
      {
        Name: 'UserId',
        Label: 'User',
        Type: 'SingleSelectLoad',
        Config: { ObjectName: 'Users', IdField: 'Id', TextField: 'UserName' },
        ReadOnly: true,
        GridField: true,
        Position: 19,
      },
      {
        Name: 'OrganizationId',
        Label: 'Organization',
        Type: 'GridLookUpSingleLoad',
        Config: {
          //Model: Models.Organization,
          ObjectName: 'Organization',
          IdField: 'Id',
          TextField: 'Name',
          MinTextLength: 0,
          SearchType: 'AllData',
          Fields: [
            { Name: 'ParentOrganization.Name', Label: 'Parent' },
            { Name: 'Id', Label: 'Id' },
            { Name: 'Name', Label: 'Name' },
            { Name: 'vwOrganizationType.label', Label: 'Type' },
            { Name: 'level', Label: 'Level' },
          ],
        },
        GridField: false,
        Position: 20,
      },

      {
        Name: 'id_data',
        Label: 'Identifiant de la fiche',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 21,
      },
      {
        Name: 'id_group',
        Label: 'Groupe',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 22,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'RadioBox',
        OptionType: 'rec_status',
        EditField: false,
        GridField: false,
        Position: 23,
      },
      {
        Name: 'user_mod',
        Label: 'Auteur de la derni',
        Type: 'Text',
        EditField: false,
        GridField: false,
        Position: 24,
      },
    ],
    [
      {
        Name: 'UserName',
        Label: 'UserName',
        Type: 'Text',
        Position: 26,
        GridField: false,
      },
      {
        Name: 'Password',
        Label: 'Password',
        Type: 'Password',
        Position: 27,
        GridField: false,
      },
      {
        Name: 'RoleId',
        Label: 'RoleId',
        Type: 'SingleSelect',
        Config: { Model: Models.Roles, IdField: 'Id', TextField: 'Name' },
        Position: 28,
        GridField: false,
      },
      {
        Name: 'date_creation',
        Label: 'Date de cr',
        Type: 'Date',
        EditField: false,
        GridField: true,
        Position: 29,
      },
    ],
    [
      {
        Name: 'Departments',
        Label: 'Departments',
        Type: 'ListView',
        Config: {
          ObjectName: 'DoctorTooDepartment',
          Fields: ['dico', 'value'],
          ForiegnKey: 'DoctorId',
        },
        md: 12,
        Position: 30,
        GridField: false,
        EditField: true,
      },
    ],
  ];

  this.ObjectName = 'DoctorsProfile';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.AttachFiles = true;
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Doctors profile',
    NewObjectTitle: 'Doctors profile create',
    EditObjectTitle: 'Doctors profile edit',
  };
}

module.exports = DoctorsProfileConfig;
