const { Models } = require('../config/DB');
const Model = Models.ExaminationEcho;
var ModelLookUp = Models.ExaminationEchoLookUp;

function ExaminationEchoConfig() {
  this.Fields = [
    [
      {
        Name: 'PatientId',
        Label: 'Patient ID',
        Type: 'GridLookUpSingleLoad',
        Config: {
          ObjectName: 'Patient',
          IdField: 'id_data',
          TextField: 'p_registration',
          Fields: [
            // { Name: "id_data", Label: "Id" },
            { Name: 'p_lastname', Label: 'Last name' },
            { Name: 'p_firstname', Label: 'first name' },
            { Name: 'p_registration', Label: 'Register' },
            { Name: 'DictProvinceCity.name', Label: 'City' },
          ],
          MinTextLength: '2',
        },
        EditField: false,
        GridField: true,
      },

      // 2025-01-23
      {
        Name: 'echo_date',
        Label: 'Шинжилгээ хийсэн огноо',
        Type: 'Date',
        GridField: true,
      },
      {
        Name: 'doctor_name',
        Label: 'Doctor name',
        Type: 'Text',
        GridField: true,
      },

      {
        Name: 'DoctorsProfile.FullName',
        Label: 'Doctor',
        Type: 'Text',
        EditField: false,
      },
      {
        Name: 'OrganizationId',
        Label: 'OrganizationId',
        Type: 'Text',
        GridField: false,
      },
      {
        Name: 'Organization.Name',
        Label: 'Organization',
        Type: 'Text',
        EditField: false,
      },
      {
        Name: 'Files',
        Label: 'Files',
        Type: 'File',
        GridField: false,
      },
      {
        Name: 'Patient.p_lastname',
        Type: 'Text',
        Label: 'Last name',
        EditField: false,
      },
      {
        Name: 'Patient.p_firstname',
        Type: 'Text',
        Label: 'First name',
        EditField: false,
      },
      {
        Name: 'Patient.p_registration',
        Type: 'Text',
        Label: 'Register',
        EditField: false,
      },
      {
        Name: 'Patient.p_birthday',
        Type: 'Text',
        Label: 'Birth date',
        EditField: false,
      },
      {
        Name: 'Patient.Age',
        Type: 'Text',
        Label: 'Age',
        EditField: false,
      },

      {
        Name: 'a',
        Label: 'A (m/s)',
        Required: true,
        Type: 'Text',
        Position: 1,
        GridField: false,
      },
      {
        Name: 'annulus_size_morph',
        Label: 'Annulus Size and Morphology',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_ansimo',
        Position: 2,
        GridField: false,
      },
      {
        Name: 'aopg',
        Label: 'AoPG (mmHg)',
        Required: true,
        Type: 'Text',
        Position: 3,
        GridField: false,
      },
      {
        Name: 'aorta',
        Label: 'Aorta (cm)',
        Type: 'Number',
        Required: true,
        Position: 4,
        GridField: false,
      },
      {
        Name: 'aortic_regurgitation',
        Label: 'Aortic regurgitation',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        Position: 5,
        GridField: false,
      },
      {
        Name: 'aortic_stenosis',
        Label: 'Aortic stenosis',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        Position: 6,
        GridField: false,
      },
      {
        Name: 'carpentier_class',
        Label: 'Carpentier Classification',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_carpclas',
        Position: 7,
        GridField: false,
      },
      {
        Name: 'comment',
        Label: 'Comment/Suggestive of',
        Type: 'Text',
        Position: 8,
        GridField: false,
      },
      {
        Name: 'date_creation',
        Label: 'Date de cr',
        Type: 'Date',
        Position: 9,
        GridField: false,
      },
      {
        Name: 'date_modif',
        Label: 'Date de modification',
        Type: 'Date',
        Position: 10,
      },
      {
        Name: 'e',
        Label: 'E (m/s)',
        Required: true,
        Type: 'Text',
        Position: 11,
        GridField: false,
      },
      {
        Name: 'e_div_a',
        Label: 'E/A',
        Required: true,
        Type: 'Text',
        Position: 12,
        GridField: false,
      },
      {
        Name: 'ef',
        Label: 'EF (%)',
        Required: true,
        Type: 'Text',
        Position: 13,
        GridField: false,
      },
      {
        Name: 'est_ra_pressure',
        Label: 'Estimated RA pressure (mm Hg)',
        Type: 'Text',
        Position: 14,
        GridField: false,
      },
      {
        Name: 'fs',
        Label: 'FS (%)',
        Required: true,
        Type: 'Text',
        Position: 15,
        GridField: false,
      },
      {
        Name: 'id',
        Label: "Identifiant d'utilisateur",
        Type: 'Text',
        Position: 16,
        GridField: false,
      },
      {
        Name: 'id_data',
        Label: 'Identifiant de la fiche',
        Type: 'Text',
        Position: 17,
        GridField: false,
      },
      {
        Name: 'id_group',
        Label: 'Groupe',
        Type: 'Text',
        Position: 18,
        GridField: false,
      },
      {
        Name: 'ivc',
        Label: 'IVC',
        Type: 'Text',
        Position: 20,
        GridField: false,
      },
      {
        Name: 'ivsd',
        Label: 'IVSd (cm)',
        Required: true,
        Type: 'Text',
        Position: 21,
        GridField: false,
      },
      {
        Name: 'ivss',
        Label: 'IVSs (cm)',
        Required: true,
        Type: 'Text',
        Position: 22,
        GridField: false,
      },
      {
        Name: 'leaf_mob_flail',
        Label: 'Flail - Anatomic localization',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_anatloc',
        Position: 23,
        GridField: false,
      },
      {
        Name: 'leaf_mob_prolapse',
        Label: 'Prolapse - Anatomic localization',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_anatloc',
        Position: 24,
        GridField: false,
      },
      {
        Name: 'leaflet_mobility',
        Label: 'Leaflet mobility',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_leamob',
        Position: 25,
        GridField: false,
      },
      {
        Name: 'left_atrial_size',
        Label: 'Left atrial size',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_leftasi',
        Position: 26,
        GridField: false,
      },
      {
        Name: 'left_atrium',
        Label: 'Left atrium (cm)',
        Required: true,
        Type: 'Number',
        Position: 27,
        GridField: false,
      },
      {
        Name: 'left_vent_size',
        Label: 'Left ventricular size',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_leftvsi',
        Position: 28,
        GridField: false,
      },
      {
        Name: 'lv_mass',
        Label: 'LV mass (gr)',
        Required: true,
        Type: 'Text',
        Position: 30,
        GridField: false,
      },
      {
        Name: 'lvdd',
        Label: 'LVDd (cm)',
        Required: true,
        Type: 'Number',
        Position: 31,
        GridField: false,
      },
      {
        Name: 'lvds',
        Label: 'LVDs (cm)',
        Required: true,
        Type: 'Text',
        Position: 32,
        GridField: false,
      },
      {
        Name: 'lvvold',
        Label: 'LVVold (ml)',
        Type: 'Text',
        Position: 33,
        GridField: false,
      },
      {
        Name: 'lvvols',
        Label: 'LVVols (ml)',
        Type: 'Text',
        Position: 34,
        GridField: false,
      },
      {
        Name: 'mitral_inflow_pro',
        Label: 'Mitral Inflow Profile',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_inflow',
        Position: 35,
        GridField: false,
      },
      {
        Name: 'mitral_regurgitation',
        Label: 'Mitral regurgitation',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        Position: 36,
        GridField: false,
      },
      {
        Name: 'mitral_stenosis',
        Label: 'Mitral Stenosis',
        Required: true,
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_mitsteno',
        Position: 37,
        GridField: false,
      },
      {
        Name: 'mr_jet_dir',
        Label: 'MR Jet Direction',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_jetdir',
        Position: 38,
        GridField: false,
      },
      {
        Name: 'mr_jet_dur',
        Label: 'MR Jet Duration',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_jetdur',
        Position: 39,
        GridField: false,
      },
      {
        Name: 'mr_jets',
        Label: 'MR Jets',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_mrjets',
        Position: 40,
        GridField: false,
      },
      {
        Name: 'mr_mrchanism',
        Label: 'MR Mrchanism',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_mrmr',
        Position: 41,
        GridField: false,
      },
      {
        Name: 'pa_sys_pressure',
        Label: 'PA systolic pressure (mm Hg)',
        Type: 'Text',
        Position: 42,
        GridField: false,
      },
      {
        Name: 'pul_vein_flow_pro',
        Label: 'Pulmonary Vein Flow Profile',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_pulvein',
        Position: 43,
        GridField: false,
      },
      {
        Name: 'pulmonary_regurgitation',
        Label: 'Pulmonary regurgitation',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        Position: 44,
        GridField: false,
      },
      {
        Name: 'pulmonary_stenosis',
        Label: 'Pulmonary stenosis',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        Position: 45,
        GridField: false,
      },
      {
        Name: 'pvpg',
        Label: 'PvPG (mmHg)',
        Required: true,
        Type: 'Text',
        Position: 46,
        GridField: false,
      },
      {
        Name: 'pwd',
        Label: 'PWd (cm)',
        Required: true,
        Type: 'Text',
        Position: 47,
        GridField: false,
      },
      {
        Name: 'pws',
        Label: 'PWs (cm)',
        Required: true,
        Type: 'Text',
        Position: 48,
        GridField: false,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'rec_status',
        Position: 49,
        GridField: false,
      },
      {
        Name: 'res_tet_leaflets',
        Label: 'Restricted or Tethered Leaflets',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_mitleaf',
        Position: 51,
        GridField: false,
      },
      {
        Name: 'right_vent_size',
        Label: 'Right ventricular size',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_mitreg_nordil',
        Position: 52,
        GridField: false,
      },
      {
        Name: 'right_vent_sys_fun',
        Label: 'Right ventricular systolic function',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_mitreg_nordil',
        Position: 53,
        GridField: false,
      },
      {
        Name: 'rvd',
        Label: 'RVd (cm)',
        Type: 'Text',
        Position: 54,
        GridField: false,
      },
      {
        Name: 'spap',
        Label: 'SPAP (mm Hg)',
        Type: 'Text',
        Position: 55,
        GridField: false,
      },
      {
        Name: 'submitral_morph',
        Label: 'Submitral morphology',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_submor',
        Position: 56,
        GridField: false,
      },
      {
        Name: 'sv',
        Label: 'SV (ml)',
        Required: true,
        Type: 'Text',
        Position: 57,
        GridField: false,
      },
      {
        Name: 'threshold_vals_mr',
        Label: 'Threshold values specific for MR',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'echo_mitreg_thrsval',
        Position: 58,
        GridField: false,
      },
      {
        Name: 'tricus_annulus',
        Label: 'Tricuspid Annulus',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_mitreg_nordil',
        GridField: false,
      },
      {
        Name: 'tricus_valv_reg',
        Label: 'Tricuspid valve regurgitation',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_mitreg_trireg',
        GridField: false,
      },
      {
        Name: 'tricuspid_regurgitation',
        Label: 'Tricuspid regurgitation',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        GridField: false,
      },
      {
        Name: 'tricuspid_stenosis',
        Label: 'Tricuspid stenosis',
        Required: true,
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'echo_valve_severity',
        GridField: false,
      },
      {
        Name: 'user_mod',
        Label: 'Auteur de la derni',
        Type: 'Text',
        GridField: false,
      },
      {
        Name: 'vena_contrata_area',
        Label: 'Vena Contrata area (cm^2)',
        Type: 'Text',
        GridField: false,
      },
      {
        Name: 'vena_contrata_width',
        Label: 'Vena Contrata width (mm)',
        Type: 'Text',
        GridField: false,
      },
      {
        Name: 'rwt',
        Label: 'RWT',
        Required: true,
        Type: 'Text',
        GridField: false,
      },
    ],
  ];

  this.ObjectName = 'ExaminationEcho';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Examination echo',
    NewObjectTitle: 'Examination echo create',
    EditObjectTitle: 'Examination echo edit',
  };
}

module.exports = ExaminationEchoConfig;
