const { Models } = require('../config/DB');
const Model = Models.FollowUp;
const ModelLookUp = Models.FollowUpLookUp;

function FollowUpConfig() {
  this.Fields = [
    [
      {
        Name: 'Files',
        Label: 'Files',
        Type: 'File',
        Position: 0,
        GridField: false,
      },
      {
        Name: 'amis_p_a_dob',
        Label: 'Date of Birth',
        Type: 'Date',
        Position: 1,
      },
      {
        Name: 'amis_p_a_gender',
        Label: 'Gender',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'sexe',
        Position: 2,
      },
      {
        Name: 'amis_p_a_heart_rhythm',
        Label: 'Heart rhythm',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'amis_heart_rhythm',
        Position: 3,
      },
      {
        Name: 'amis_p_a_heart_rhythm_other',
        Label: 'Other',
        Type: 'Text',
        Position: 4,
      },
      {
        Name: 'amis_qstnr',
        Label: 'AMIS Plus Questionnaire',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'amis_questionnaire',
        Position: 5,
      },
      {
        Name: 'biochemyorn',
        Label: 'Biochemistry test',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality2',
        Position: 6,
      },
      {
        Name: 'cbcyorn',
        Label: 'CBC test',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality2',
        Editfield: false,
        Position: 7,
      },
      {
        Name: 'cir_ab',
        Label: 'Circulatory system status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 8,
      },
      {
        Name: 'date_creation',
        Label: 'Date de cr',
        Type: 'Date',
        Editfield: false,
        Position: 9,
      },
      {
        Name: 'date_modif',
        Label: 'Date de modification',
        Type: 'Date',
        Editfield: false,
        Position: 10,
      },
      {
        Name: 'ecgyorn',
        Label: 'ECG examination',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 11,
      },
      {
        Name: 'fu_bio_albumin',
        Label: 'Albumin',
        Type: 'Text',
        Editfield: false,
        Position: 12,
      },
      {
        Name: 'fu_bio_amilase',
        Label: 'Amilaze (u/L)',
        Type: 'Text',
        Editfield: false,
        Position: 13,
      },
      {
        Name: 'fu_bio_cholesterol',
        Label: 'Cholesterol',
        Type: 'Text',
        Editfield: false,
        Position: 14,
      },
      {
        Name: 'fu_bio_creatinine',
        Label: 'Creatinine',
        Type: 'Text',
        Editfield: false,
        Position: 15,
      },
      {
        Name: 'fu_bio_got',
        Label: 'GOT (u/L)',
        Type: 'Text',
        Editfield: false,
        Position: 16,
      },
      {
        Name: 'fu_bio_gpt',
        Label: 'GPT (u/L)',
        Type: 'Text',
        Editfield: false,
        Position: 17,
      },
      {
        Name: 'fu_bio_ldg',
        Label: 'LDG (u/L)',
        Type: 'Text',
        Editfield: false,
        Position: 18,
      },
      {
        Name: 'fu_bio_mochevin',
        Label: 'Mochevin (mmol/L)',
        Type: 'Text',
        Editfield: false,
        Position: 19,
      },
      {
        Name: 'fu_bio_other',
        Label: 'Other',
        Type: 'Text',
        Editfield: false,
        Position: 20,
      },
      {
        Name: 'fu_bio_potassium',
        Label: 'Potassium (mmol/L)',
        Type: 'Text',
        Editfield: false,
        Position: 21,
      },
      {
        Name: 'fu_bio_protein',
        Label: 'Total protein (g/L)',
        Type: 'Text',
        Editfield: false,
        Position: 22,
      },
      {
        Name: 'fu_bio_sodium',
        Label: 'Sodium (mmol/L)',
        Type: 'Text',
        Editfield: false,
        Position: 23,
      },
      {
        Name: 'fu_bio_sugar',
        Label: 'Sugar (mmol/L)',
        Type: 'Text',
        Editfield: false,
        Position: 24,
      },
      {
        Name: 'fu_bio_uldegdel',
        Label: 'Uldegdel azot (mmol/L)',
        Type: 'Text',
        Editfield: false,
        Position: 25,
      },
      {
        Name: 'fu_c_comp',
        Label: 'Comment on chief complaint',
        Type: 'Text',
        Editfield: false,
        Position: 26,
      },
      {
        Name: 'fu_c_comp_code',
        Label: 'Chief complaint',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'ccomplaint',
        Editfield: false,
        Position: 27,
      },
      {
        Name: 'stroke_chief_complaint',
        Label: 'Chief complaint',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'stroke_ccomplaint',
        Editfield: false,
        Position: 27,
      },
      {
        Name: 'fu_c_diag',
        Label: 'Comment to co-existing diagnosis',
        Type: 'Text',
        Editfield: false,
        Position: 28,
      },
      {
        Name: 'fu_c_diag_code',
        Label: 'Coexisting diagnosis ICD10',
        Type: 'SingleSelectLoad',
        Config: {
          ObjectName: 'vwICD10',
          IdField: 'value',
          TextField: 'label',
          MinTextLength: 1,
        },
        Editfield: false,
        Position: 29,
      },
      {
        Name: 'fu_cbc_esr',
        Label: 'ESR (mm/h)',
        Type: 'Text',
        Editfield: false,
        Position: 30,
      },
      {
        Name: 'fu_cbc_hematocrit',
        Label: 'Hematocrit (%)',
        Type: 'Text',
        Editfield: false,
        Position: 31,
      },
      {
        Name: 'fu_cbc_hemoglobin',
        Label: 'Hemoglobin (g/dL)',
        Type: 'Text',
        Editfield: false,
        Position: 32,
      },
      {
        Name: 'fu_cbc_other',
        Label: 'Other / Comment',
        Type: 'Text',
        Editfield: false,
        Position: 33,
      },
      {
        Name: 'fu_cbc_platelet',
        Label: 'Platelet (*10e9/L)',
        Type: 'Text',
        Editfield: false,
        Position: 34,
      },
      {
        Name: 'fu_cbc_r_blood',
        Label: 'Red blood cell (*10e9/L)',
        Type: 'Text',
        Editfield: false,
        Position: 35,
      },
      {
        Name: 'fu_cbc_w_blood',
        Label: 'White blood cell (4-8*10e9/L)',
        Type: 'Text',
        Editfield: false,
        Position: 36,
      },
      {
        Name: 'fu_d_bp',
        Label: 'Diastolic pressure',
        Type: 'Text',
        Editfield: false,
        Position: 37,
      },
      {
        Name: 'fu_ecg_concl',
        Label: 'ECG Conclusion',
        Type: 'Text',
        Editfield: false,
        Position: 38,
      },
      {
        Name: 'fu_echo_concl',
        Label: 'Conclusion',
        Type: 'Text',
        Editfield: false,
        Position: 39,
      },
      {
        Name: 'fu_history_ill',
        Label: 'History of present illness',
        Type: 'Text',
        Editfield: false,
        Position: 40,
      },
      {
        Name: 'fu_hosp_date',
        Label: 'Date of visit',
        Type: 'Date',
        Editfield: false,
        Position: 41,
      },
      {
        Name: 'fu_m_diag',
        Label: 'Comment to main diagnosis',
        Type: 'Text',
        Editfield: false,
        Position: 42,
      },
      {
        Name: 'fu_m_diag_code',
        Label: 'Main diagnosis ICD10',
        Type: 'SingleSelectLoad',
        Config: {
          ObjectName: 'vwICD10',
          IdField: 'value',
          TextField: 'label',
          MinTextLength: 1,
        },
        Editfield: false,
        Position: 43,
      },
      {
        Name: 'fu_other_abdo',
        Label: 'Abdominal ultrasound',
        Type: 'Text',
        Editfield: false,
        Position: 44,
      },
      {
        Name: 'fu_other_other',
        Label: 'Other',
        Type: 'Text',
        Editfield: false,
        Position: 45,
      },
      {
        Name: 'fu_other_xray',
        Label: 'X-Ray',
        Type: 'Text',
        Editfield: false,
        Position: 46,
      },
      {
        Name: 'fu_pe_circ_sys',
        Label: 'Circulatory system',
        Type: 'Text',
        Editfield: false,
        Position: 47,
      },
      {
        Name: 'fu_pe_circ_sys_code',
        Label: 'Murmur',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'heart',
        Editfield: false,
        Position: 48,
      },
      {
        Name: 'fu_pe_circ_sys_code1',
        Label: 'Murmurs',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'heart',
        Editfield: false,
        Position: 49,
      },
      {
        Name: 'fu_pe_circ_sys_code2',
        Label: 'Murmurs',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'heart',
        Editfield: false,
        Position: 50,
      },
      {
        Name: 'fu_pe_circ_sys_code3',
        Label: 'Murmurs',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'heart',
        Editfield: false,
        Position: 51,
      },
      {
        Name: 'fu_pe_circ_sys_loc_code',
        Label: 'Auscultation location',
        Type: 'Text',
        Editfield: false,
        Position: 52,
      },
      {
        Name: 'fu_pe_gast_sys',
        Label: 'Gastrointestinal system',
        Type: 'Text',
        Editfield: false,
        Position: 53,
      },
      {
        Name: 'fu_pe_gast_sys_code',
        Label: 'Gastrology PE coded',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'liver',
        Editfield: false,
        Position: 54,
      },
      {
        Name: 'fu_pe_heent',
        Label: 'HEENT',
        Type: 'Text',
        Editfield: false,
        Position: 55,
      },
      {
        Name: 'fu_pe_joint_code',
        Label: 'Joint PE coded',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'joints',
        Editfield: false,
        Position: 56,
      },
      {
        Name: 'fu_pe_joints',
        Label: 'Joints',
        Type: 'Text',
        Editfield: false,
        Position: 57,
      },
      {
        Name: 'fu_pe_loc_ao',
        Label: 'Aortic area murmur',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        Editfield: false,
        Position: 58,
      },
      {
        Name: 'fu_pe_loc_mv',
        Label: 'Mitral area murmur',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        Editfield: false,
        Position: 59,
      },
      {
        Name: 'fu_pe_loc_pv',
        Label: 'Pulmonary area murmur',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        Editfield: false,
        Position: 60,
      },
      {
        Name: 'fu_pe_loc_tv',
        Label: 'Tricuspid area murmur',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        Editfield: false,
        Position: 61,
      },
      {
        Name: 'fu_pe_muscle',
        Label: 'Muscle',
        Type: 'Text',
        Editfield: false,
        Position: 62,
      },
      {
        Name: 'fu_pe_muscle_code',
        Label: 'Muscle PE coded',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'muscles',
        Editfield: false,
        Position: 63,
      },
      {
        Name: 'fu_pe_nephrology',
        Label: 'Nephrology',
        Type: 'Text',
        Editfield: false,
        Position: 64,
      },
      {
        Name: 'fu_pe_nephrology_code',
        Label: 'Nephrology PE coded',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'edema',
        Editfield: false,
        Position: 65,
      },
      {
        Name: 'fu_pe_other',
        Label: 'Other',
        Type: 'Text',
        Editfield: false,
        Position: 66,
      },
      {
        Name: 'fu_pe_resp_llung',
        Label: 'Abnormality in left lung',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        Editfield: false,
        Position: 67,
      },
      {
        Name: 'fu_pe_resp_rlung',
        Label: 'Abnormality in right lung',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        Editfield: false,
        Position: 68,
      },
      {
        Name: 'fu_pe_resp_sys',
        Label: 'Respiratory system',
        Type: 'Text',
        Editfield: false,
        Position: 69,
      },
      {
        Name: 'fu_pe_resp_sys_code',
        Label: 'Respiratory PE coded',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'lung',
        Editfield: false,
        Position: 70,
      },
      {
        Name: 'fu_pe_resp_sys_code1',
        Label: 'Respiratory PE Coded1',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'lung',
        Editfield: false,
        Position: 71,
      },
      {
        Name: 'fu_pe_severity',
        Label: 'Patient severity',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'severity',
        Editfield: false,
        Position: 72,
      },
      {
        Name: 'fu_pe_skin',
        Label: 'Skin',
        Type: 'Text',
        Editfield: false,
        Position: 73,
      },
      {
        Name: 'fu_pe_skin_code',
        Label: 'Skin PE coded',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        OptionType: 'skin',
        Editfield: false,
        Position: 74,
      },
      {
        Name: 'fu_pe_vs_heart',
        Label: 'Heart rate',
        Type: 'Text',
        Editfield: false,
        Position: 75,
      },
      {
        Name: 'fu_pe_vs_urine',
        Label: '24 hour Urine (ml)',
        Type: 'Text',
        Editfield: false,
        Position: 76,
      },
      {
        Name: 'fu_resp',
        Label: 'Respiratory rate',
        Type: 'Text',
        Editfield: false,
        Position: 77,
      },
      {
        Name: 'fu_s_bp',
        Label: 'Systolic pressure',
        Type: 'Text',
        Editfield: false,
        Position: 78,
      },
      {
        Name: 'fu_temp',
        Label: 'Body temperature',
        Type: 'Text',
        Editfield: false,
        Position: 79,
      },
      {
        Name: 'fu_urine_bilirubin',
        Label: 'Bilirubin',
        Type: 'Text',
        Editfield: false,
        Position: 80,
      },
      {
        Name: 'fu_urine_bulingar',
        Label: 'Bulingar',
        Type: 'Text',
        Editfield: false,
        Position: 81,
      },
      {
        Name: 'fu_urine_color',
        Label: 'Color',
        Type: 'Text',
        Editfield: false,
        Position: 82,
      },
      {
        Name: 'fu_urine_ketonii',
        Label: 'Ketonii biy',
        Type: 'Text',
        Editfield: false,
        Position: 83,
      },
      {
        Name: 'fu_urine_khuviin',
        Label: 'Khuviin jin (mg/100ml)',
        Type: 'Text',
        Editfield: false,
        Position: 84,
      },
      {
        Name: 'fu_urine_nitrit',
        Label: 'Nitrit (mg/100ml)',
        Type: 'Text',
        Editfield: false,
        Position: 85,
      },
      {
        Name: 'fu_urine_other',
        Label: 'Other',
        Type: 'Text',
        Editfield: false,
        Position: 86,
      },
      {
        Name: 'fu_urine_ph',
        Label: 'pH (mg/100ml)',
        Type: 'Text',
        Editfield: false,
        Position: 87,
      },
      {
        Name: 'fu_urine_protein',
        Label: 'Protein (g/L)',
        Type: 'Text',
        Editfield: false,
        Position: 88,
      },
      {
        Name: 'fu_urine_r_blood',
        Label: 'Red blood cell (RBC/ml)',
        Type: 'Text',
        Editfield: false,
        Position: 89,
      },
      {
        Name: 'fu_urine_rbc_micr',
        Label: 'RBC in microscope (Visual space)',
        Type: 'Text',
        Editfield: false,
        Position: 90,
      },
      {
        Name: 'fu_urine_sugar',
        Label: 'Sugar',
        Type: 'Text',
        Editfield: false,
        Position: 91,
      },
      {
        Name: 'fu_urine_urobilinogen',
        Label: 'Urobilinogen',
        Type: 'Text',
        Editfield: false,
        Position: 92,
      },
      {
        Name: 'fu_urine_volume',
        Label: 'Volume (ml)',
        Type: 'Text',
        Editfield: false,
        Position: 93,
      },
      {
        Name: 'fu_urine_w_blood',
        Label: 'White blood cell (WBC/ml)',
        Type: 'Text',
        Editfield: false,
        Position: 94,
      },
      {
        Name: 'fu_urine_wbc_micr',
        Label: 'WBC in microscope (Visual space)',
        Type: 'Text',
        Editfield: false,
        Position: 95,
      },
      {
        Name: 'fu_vs_bodyweight',
        Label: 'Body weight (kg)',
        Type: 'Text',
        Editfield: false,
        Position: 96,
      },
      {
        Name: 'fu_vs_height',
        Label: 'Height (meter)',
        Type: 'Text',
        Editfield: false,
        Position: 97,
      },
      {
        Name: 'gas_ab',
        Label: 'Gastroenterology system status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 98,
      },
      {
        Name: 'heent_ab',
        Label: 'HEENT status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 99,
      },
      {
        Name: 'id',
        Label: "Identifiant d'utilisateur",
        Type: 'Text',
        Editfield: false,
        Position: 100,
      },
      {
        Name: 'id_data',
        Label: 'Identifiant de la fiche',
        Type: 'Text',
        Editfield: false,
        Position: 101,
      },
      {
        Name: 'id_group',
        Label: 'Groupe',
        Type: 'Text',
        Editfield: false,
        Position: 102,
      },
      {
        Name: 'joints_ab',
        Label: 'Joints status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 104,
      },
      {
        Name: 'muscle_ab',
        Label: 'Muscle status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 106,
      },
      {
        Name: 'neph_ab',
        Label: 'Nephrology system status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 107,
      },
      {
        Name: 'olabyorn1',
        Label: 'Other Lab test 1',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 108,
      },
      {
        Name: 'olabyorn2',
        Label: 'Other lab test 2',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 109,
      },
      {
        Name: 'olabyorn3',
        Label: 'Other lab test 3',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 110,
      },
      {
        Name: 'olabyorn4',
        Label: 'Other lab test 4',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 111,
      },
      {
        Name: 'oth_ab',
        Label: 'Other system status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 112,
      },
      {
        Name: 'other1',
        Label: 'Other laboratory test',
        Type: 'Text',
        Editfield: false,
        Position: 113,
      },
      {
        Name: 'other2',
        Label: 'Other lab 2',
        Type: 'Text',
        Editfield: false,
        Position: 114,
      },
      {
        Name: 'other3',
        Label: 'Other lab 3',
        Type: 'Text',
        Editfield: false,
        Position: 115,
      },
      {
        Name: 'other4',
        Label: 'Other lab 4',
        Type: 'Text',
        Editfield: false,
        Position: 116,
      },
      {
        Name: 'otherimagesyorn',
        Label: 'Other image examination',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 117,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'rec_status',
        Editfield: false,
        Position: 118,
      },
      {
        Name: 'res_ab',
        Label: 'Respiratory system status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 120,
      },
      {
        Name: 'skin_ab',
        Label: 'Skin status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality',
        Editfield: false,
        Position: 121,
      },
      {
        Name: 'ultrasoundyorn',
        Label: 'Ultrasound examination',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'posneg',
        Editfield: false,
        Position: 122,
      },
      {
        Name: 'urineyorn',
        Label: 'Urine test',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'normality2',
        Editfield: false,
        Position: 123,
      },
      {
        Name: 'user_mod',
        Label: 'Auteur de la derni',
        Type: 'Text',
        Editfield: false,
        Position: 124,
      },
    ],
  ];

  this.ObjectName = 'FollowUp';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Follow Up',
    NewObjectTitle: 'Follow Up create',
    EditObjectTitle: 'Follow Up edit',
  };
}

module.exports = FollowUpConfig;
