const { Models } = require('../config/DB');
const Model = Models.LookupDoctorTeam;

function LookupDoctorTeamConfig() {
  this.Fields = [
    [
      {
        Name: 'date_creation',
        Label: 'Creation date',
        Type: 'Date',
        md: 4,
        Position: 20,
      },
      {
        Name: 'date_modif',
        Label: 'Update date',
        Type: 'Date',
        md: 4,
        Position: 2,
        GridField: false,
        EditField: false,
      },
      {
        Name: 'doctor_id',
        Label: 'Doctor profile ID',
        Type: 'GridLookUpSingleLoad',
        Config: {
          ObjectName: 'DoctorsProfile',
          IdField: 'id_data',
          TextField: 'firstname',
          MinTextLength: 1,
          Fields: [
            { Label: 'Last name', Name: 'lastname' },
            { Label: 'First name', Name: 'firstname' },
            { Label: 'Email', Name: 'email' },
          ],
        },
        md: 4,
        Position: 3,
        GridField: false,
        EditField: true,
      },
      {
        Name: 'DoctorsProfile.lastname',
        Label: 'Last name',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.firstname',
        Label: 'First name',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.Province.label',
        Label: 'Province City',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.organisation',
        Label: 'Workplace',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.profession',
        Label: 'Profession',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.email',
        Label: 'Email',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.telephone',
        Label: 'Telephone',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: false,
      },
      {
        Name: 'id',
        Label: 'User ID',
        Type: 'Text',
        md: 4,
        Position: 4,
        GridField: false,
        EditField: false,
      },
      {
        Name: 'id_data',
        Label: 'Record ID',
        Type: 'Text',
        md: 4,
        Position: 5,
        GridField: false,
        EditField: false,
      },
      {
        Name: 'id_group',
        Label: 'Group',
        Type: 'Text',
        md: 4,
        Position: 6,
        GridField: false,
        EditField: false,
      },
      {
        Name: 'privilege_add_patient',
        Label: 'Privilege add patient',
        Type: 'SingleCheckBox',
        md: 4,
        Position: 9,
      },
      {
        Name: 'privilege_admin',
        Label: 'Privilege admin',
        Type: 'SingleCheckBox',
        md: 4,
        Position: 10,
      },
      {
        Name: 'privilege_delete_patient',
        Label: 'Privilege delete patient',
        Type: 'SingleCheckBox',
        md: 4,
        Position: 11,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'rec_status',
        Position: 12,
        GridField: false,
      },
      {
        Name: 'team_id',
        Label: 'Team ID',
        Type: 'GridLookUpSingleLoad',
        Config: {
          ObjectName: 'DoctorsTeam',
          IdField: 'id_data',
          TextField: 'name',
          MinTextLength: 1,
          Fields: [{ Label: 'Name', Name: 'name' }],
        },
        md: 4,
        Position: 14,
        GridField: false,
        EditField: true,
      },
      {
        Name: 'DoctorsTeam.name',
        Label: 'Багийн нэр',
        Type: 'Text',
        md: 4,
        Position: 15,
        EditField: false,
      },
      {
        Name: 'DoctorsTeam.extra_info',
        Label: 'Enum for extra information',
        Type: 'Text',
        md: 4,
        Position: 16,
        EditField: false,
      },
      {
        Name: 'DoctorsProfile.date_creation',
        Label: 'Баг үүсгэсэн огноо',
        Type: 'Text',
        md: 4,
        Position: 17,
        EditField: false,
      },
      {
        Name: 'user_mod',
        Label: 'Last update author',
        Type: 'Text',
        md: 4,
        Position: 15,
        GridField: false,
        EditField: false,
      },
      {
        Name: 'Users.UserName',
        Label: 'User',
        Type: 'Text',
        md: 4,
        Position: 15,
        EditField: false,
      },
    ],
  ];

  this.ObjectName = 'LookupDoctorTeam';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Doctor_team_lookup',
    NewObjectTitle: 'Doctor_team_lookup create',
    EditObjectTitle: 'Doctor_team_lookup edit',
  };
}

module.exports = LookupDoctorTeamConfig;
