const { Models } = require('../config/DB');
const Model = Models.Patient;
var ModelLookUp = Models.PatientLookUp;

function PatientConfig() {
  this.Fields = [
    [
      {
        Name: 'Files',
        Label: 'Profile image',
        Type: 'SingleImage',
        md: 4,
        EditField: true,
        GridField: false,
      },
    ],
    [
      {
        Name: 'p_lastname',
        Label: 'Last name',
        Type: 'Text',
        md: 3,
        Position: 1,
        EditField: true,
      },
      {
        Name: 'p_firstname',
        Label: 'First name',
        Type: 'Text',
        md: 3,
        Position: 2,
        EditField: true,
      },
      {
        Name: 'p_familyname',
        Label: 'Family name',
        Type: 'Text',
        md: 4,
        Position: 3,
        EditField: true,
      },
    ],
    [
      {
        Name: 'p_gender',
        Label: 'Gender',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'sexe',
        Position: 4,
        EditField: true,
      },
      {
        Name: 'p_is_married',
        Label: 'Marriage',
        Type: 'RadioBox',
        md: 4,
        Position: 6,
        OptionType: 'marriage',
        Config: { IdField: 'Value', TextField: 'Label' },
        GridField: false,
        EditField: true,
      },
      {
        Name: 'p_birthday',
        Label: 'Birthday',
        Type: 'Date',
        md: 4,
        Position: 5,
        EditField: true,
      },
      {
        Name: 'p_age',
        Label: 'Age',
        Type: 'Number',
        md: 4,
        Position: 5,
        GridField: true,
        EditField: true,
      },

      {
        Name: 'p_ethnicity',
        Label: 'Ethnicity',
        Type: 'RadioBox',
        md: 4,
        Config: { TextField: 'Label', IdField: 'Value' },
        OptionType: 'ethnicity',
        Position: 8,
        GridField: false,
      },
      {
        Name: 'p_ethnicity_other',
        Label: 'Ethnicity other',
        Type: 'Text',
        md: 4,
        Position: 6,
      },
      {
        Name: 'p_registration',
        Label: 'Personal number',
        Type: 'Text',
        md: 4,
        Position: 6,
        EditField: true,
      },
      {
        Name: 'Age',
        Label: 'Age',
        Type: 'Virtual',
        md: 4,
        Position: 7,
        EditField: false,
      },
      {
        Name: 'blood_type',
        Label: 'Blood type',
        Type: 'RadioBox',
        md: 4,
        Config: { TextField: 'Label', IdField: 'Value' },
        OptionType: 'blood_type',
        Position: 8,
        GridField: false,
        EditField: true,
      },
      {
        Name: 'user_id',
        Label: 'Linked User',
        Type: 'SingleSelectLoad',
        md: 4,
        Config: {
          ObejctName: 'PatientUsers',
          TextField: 'UserName',
          IdField: 'Id',
        },
        DataFilter: [{ Field: 'RoleId', Value: '4', Op: 'Equals' }],
        Position: 9,
        GridField: false,
      },
    ],
    [
      {
        Name: 'DictProvinceCity.name',
        Label: 'Province/city',
        Type: 'Text',
        Position: 1,
        ReadOnly: true,
        GridField: true,
        EditField: false,
      },
      {
        Name: 'DictSoumDistrict.name',
        Label: 'Soum/district',
        Type: 'Text',
        Position: 10,
        GridField: true,
        EditField: false,
      },
      {
        Name: 'DictBagKhoroo.name',
        Label: 'Bag/khoroo',
        Type: 'Text',
        Position: 11,
        GridField: true,
        EditField: false,
      },
      {
        Name: 'addr_prov_city',
        Label: 'Province/city',
        Type: 'SingleSelect',
        md: 4,
        Config: {
          Model: Models.DictProvinceCity,
          IdField: 'id_data',
          TextField: 'name',
          MinTextLength: 1,
        },
        GridField: false,
        Position: 12,
      },
      {
        Name: 'addr_soum_dist',
        Label: 'Soum/district',
        Type: 'SingleSelect',
        md: 4,
        Config: {
          SearchType: 'AllData',
          Model: Models.DictSoumDistrict,
          ObjectName: 'DictSoumDistrict',
          IdField: 'id_data',
          TextField: 'name',
          MinTextLength: 0,
          Fields: [
            { Name: 'id_data', Label: 'Id' },
            { Name: 'name', Label: 'Name' },
          ],
        },
        GridField: false,
        Position: 13,
      },
      {
        Name: 'addr_bag_khoroo',
        Label: 'Bag/khoroo',
        Type: 'SingleSelect',
        md: 4,
        GridField: false,
        Config: {
          SearchType: 'AllData',
          Model: Models.DictBagKhoroo,
          ObjectName: 'DictBagKhoroo',
          IdField: 'id_data',
          TextField: 'name',
          MinTextLength: 0,
          Fields: [
            { Name: 'id_data', Label: 'Id' },
            { Name: 'name', Label: 'Name' },
          ],
        },
        Position: 13,
      },
    ],
    [
      {
        Name: 'p_address',
        Label: 'Living address',
        Type: 'TextArea',
        md: 4,
        GridField: false,
        Position: 14,
        EditField: true,
      },
      {
        Name: 'p_temp_address',
        Label: 'Temporary address',
        Type: 'TextArea',
        md: 4,
        GridField: false,
        Position: 14,
        EditField: true,
      },
      {
        Name: 'province',
        Label: 'Province',
        Type: 'SingleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'aimag',
        GridField: false,
        Position: 15,
      },
      {
        Name: 'p_occupation',
        Label: 'Occupation',
        Type: 'Text',
        md: 4,
        GridField: false,
        Position: 16,
      },
    ],
    [
      {
        Name: 'p_education',
        Label: 'Education',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'education',
        GridField: false,
        Position: 17,
      },
      {
        Name: 'p_workplace',
        Label: 'Workplace (for children in kindergarden, school or at home)',
        Type: 'Text',
        md: 4,
        GridField: false,
        Position: 18,
      },
      {
        Name: 'p_employeement',
        Label: 'Ажил эрхлэлтийн байдал',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        Data: [
          { Label: 'Ажилтай', Value: '1' },
          { Label: 'Хувийн хэвшил', Value: '2' },
          { Label: 'Ажилгүй', Value: '3' },
          { Label: 'Тэтгэвэрт', Value: '4' },
          { Label: 'Групп', Value: '5' },
          { Label: 'Оюутан', Value: '6' },
          { Label: 'Малчин', Value: '7' },
        ],
        EditField: true,
      },
      {
        Name: 'p_health_insurance',
        Label: 'Health insurance',
        Type: 'Text',
        md: 4,
        GridField: false,
        Position: 19,
      },
    ],
    [
      {
        Name: 'p_telephone',
        Label: 'Утасны дугаар №1',
        Type: 'Number',
        md: 4,
        Position: 20,
      },
      {
        Name: 'p_telephone2',
        Label: 'Утасны дугаар №2',
        Type: 'Number',
        md: 4,
        Position: 20,
      },
      {
        Name: 'p_social_hist_code',
        Label: 'Social history coded',
        Type: 'MultipleSelect',
        Config: { IdField: 'Value', TextField: 'Label' },

        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'socialstatus',
        GridField: false,
        Position: 21,
      },
      {
        Name: 'p_soc_hist',
        Label: 'Social history',
        Type: 'Text',
        md: 4,
        GridField: false,
        Position: 22,
      },
    ],
    [
      {
        Name: 'p_com_dis_code',
        Label: 'Communicable disease code',
        Type: 'MultipleSelect',
        Multiple: true,
        md: 4,
        OptionType: 'comdisease',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        GridField: false,
        Position: 23,
      },
      {
        Name: 'p_com_dis',
        Label: 'Major communicable disease',
        Type: 'Text',
        md: 4,
        GridField: false,
        Position: 24,
      },
    ],
    [
      {
        Name: 'p_noncom_dis_code',
        Label: 'Noncommunicable disease code',
        Type: 'CheckBox',
        Multiple: true,
        md: 6,
        OptionType: 'noncomdisease',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        GridField: false,
        Position: 25,
      },
      {
        Name: 'p_noncom_dis',
        Label: 'Major non-communicable disease',
        Type: 'Text',
        md: 6,
        GridField: false,
        Position: 26,
      },
    ],
    [
      {
        Name: 'p_operations_code',
        Label: 'Operations coded',
        Type: 'CheckBox',
        Multiple: true,
        md: 6,
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'operation',
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        GridField: false,
        Position: 27,
      },
      {
        Name: 'p_operations',
        Label: 'Major operations',
        Type: 'TextArea',
        md: 6,
        GridField: false,
        Position: 28,
      },
    ],
    [
      {
        Name: 'p_trauma_code',
        Label: 'Trauma coded',
        Type: 'CheckBox',
        Multiple: true,
        md: 4,
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'trauma',
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        GridField: false,
        Position: 29,
      },
      {
        Name: 'p_trauma',
        Label: 'Major trauma',
        Type: 'Text',
        md: 4,
        GridField: false,
        Position: 30,
      },
    ],
    [
      {
        Name: 'p_fam_hist_code',
        Label: 'Family history coded',
        Type: 'CheckBox',
        Multiple: true,
        md: 4,
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'familyhistory',
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        GridField: false,
        Position: 31,
      },
      {
        Name: 'p_fam_hist',
        Label: 'Family history',
        Type: 'TextArea',
        md: 4,
        GridField: false,
        Position: 32,
      },
    ],
    [
      {
        Name: 'Users.UserName',
        Label: 'Create user',
        Type: 'Text',
        md: 4,
        EditField: false,
        GridField: true,
        Position: 33,
      },
      {
        Name: 'date_creation',
        Label: 'Date de cr',
        Type: 'Date',
        md: 4,
        EditField: false,
        Position: 34,
      },
      {
        Name: 'date_modif',
        Label: 'Date de modification',
        Type: 'Date',
        md: 4,
        EditField: false,
        GridField: false,
      },
      {
        Name: 'id',
        Label: "Identifiant d'utilisateur",
        Type: 'Text',
        md: 4,
        EditField: false,
        GridField: false,
      },
      {
        Name: 'id_data',
        Label: 'Identifiant de la fiche',
        Type: 'Text',
        md: 4,
        EditField: false,
        GridField: false,
      },
      {
        Name: 'id_group',
        Label: 'Groupe',
        Type: 'Text',
        md: 4,
        EditField: false,
        GridField: false,
      },
      {
        Name: 'p_c_yorn',
        Label: 'Communicable disease history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn3',
        EditField: false,
        GridField: false,
      },

      {
        Name: 'p_family_yorn',
        Label: 'Family history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn3',
        EditField: false,
        GridField: false,
      },

      {
        Name: 'p_med_hist',
        Label: 'Past medical history',
        Type: 'Text',
        md: 4,
        EditField: false,
        GridField: false,
      },
      {
        Name: 'p_nonc_yorn',
        Label: 'Noncommunicable disease history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn3',
        EditField: false,
        GridField: false,
      },

      {
        Name: 'p_oper_yorn',
        Label: 'Major operation history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn3',
        EditField: false,
        GridField: false,
      },

      {
        Name: 'p_rfactor',
        Label: 'Major risk factors',
        Type: 'MultipleSelect',
        Multiple: true,
        md: 4,
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'rfactor',
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        GridField: false,
        Position: 35,
      },
      {
        Name: 'p_soc_histyorn',
        Label: 'Social history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn3',
        EditField: false,
        GridField: false,
      },
      {
        Name: 'p_trauma_yorn',
        Label: 'Major trauma history',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn3',
        EditField: false,
        GridField: false,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'rec_status',
        EditField: false,
        GridField: false,
      },
      {
        Name: 'ubdistricts',
        Label: 'Districts of UB',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'district',
        EditField: false,
        GridField: false,
      },
      {
        Name: 'user_mod',
        Label: 'Auteur de la derni',
        Type: 'Text',
        md: 4,
        EditField: false,
        GridField: false,
      },
    ],
  ];

  this.ObjectName = 'Patient';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.AttachFiles = true;
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Patient',
    NewObjectTitle: 'Patient create',
    EditObjectTitle: 'Patient edit',
  };
}

module.exports = PatientConfig;
