const { Models } = require('../config/DB');
const Model = Models.Visit;
var ModelLookUp = Models.VisitLookUp;

function VisitConfig() {
  this.Fields = [
    [
      {
        Name: 'PatientId',
        Label: 'Patient ID',
        Type: 'GridLookUpSingleLoad',
        Config: {
          ObjectName: 'Patient',
          IdField: 'id_data',
          TextField: 'p_registration',
          Fields: [
            // { Name: "id_data", Label: "Id" },
            { Name: 'p_lastname', Label: 'Last name' },
            { Name: 'p_firstname', Label: 'first name' },
            { Name: 'p_registration', Label: 'Register' },
            { Name: 'DictProvinceCity.name', Label: 'City' },
          ],
          MinTextLength: '2',
        },
        EditField: false,
        GridField: false,
        Position: 1,
        md: 4,
      },
      { Name: 'PatRegNo', Label: 'Рersonal number', Type: 'Text' },
      {
        Name: 'DoctorsProfile.FullName',
        Label: 'Doctor',
        Type: 'Text',
        Position: 2,
        EditField: false,
      },
      {
        Name: 'OrganizationId',
        Label: 'OrganizationId',
        Type: 'Text',
        md: 4,
        Position: 3,
        GridField: false,
      },
      {
        Name: 'Organization.Name',
        Label: 'Organization',
        Type: 'Text',
        md: 4,
        Position: 4,
        EditField: false,
      },
      {
        Name: 'Files',
        Label: 'Files',
        Type: 'File',
        md: 4,
        Position: 5,
        GridField: false,
      },
      {
        Name: 'visit_date',
        Label: 'Date of visit',
        Required: true,
        Type: 'Date',
        md: 4,
        Position: 6,
      },
      {
        Name: 'Patient.p_lastname',
        Type: 'Text',
        Label: 'Last name',
        EditField: false,
        Position: 7,
      },
      {
        Name: 'Patient.p_firstname',
        Type: 'Text',
        Label: 'First name',
        EditField: false,
        Position: 8,
      },
      {
        Name: 'Patient.p_registration',
        Type: 'Text',
        Label: 'Personal number',
        EditField: false,
        GridField: false,
        Position: 9,
      },
      {
        Name: 'Patient.p_birthday',
        Type: 'Text',
        Label: 'Birth date',
        EditField: false,
        Position: 10,
      },
      {
        Name: 'Patient.Age',
        Type: 'Text',
        Label: 'Age',
        EditField: false,
        Position: 11,
      },
      {
        Name: 'date_modif',
        Label: 'Date de modification',
        Type: 'Date',
        md: 4,
        Position: 12,
        EditField: false,
      },
      {
        Name: 'c_doctor',
        Label: 'Doctor performed',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'cathlab_doctor',
        Position: 13,
        GridField: false,
      },
      {
        Name: 'c_procedure',
        Label: 'Procedure performed',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'procedure_performed',
        Position: 14,
        GridField: false,
      },
      { Name: 'Notes', Label: 'Notes', Type: 'Text' },
      {
        Name: 'c_result',
        Label: 'Result',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'cathlab_result',
        Position: 15,
        GridField: false,
      },
      {
        Name: 'c_treatment',
        Label: 'Treatment',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'cathlab_ttt',
        Position: 16,
        GridField: false,
      },
      {
        Name: 'cathlab_test',
        Label: 'Test',
        Type: 'Text',
        md: 4,
        Position: 17,
        GridField: false,
      },
      {
        Name: 'chief_complaint',
        Label: 'Chief complaint',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'ccomplaint',
        Position: 18,
        GridField: false,
      },
      {
        Name: 'stroke_chief_complaint',
        Label: 'Chief complaint',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'stroke_ccomplaint',
        Position: 19,
        GridField: false,
      },
      {
        Name: 'd_bp',
        Label: 'Diastolic pressure',
        Type: 'Number',
        md: 4,
        Position: 20,
        GridField: false,
      },
      {
        Name: 'date_creation',
        Label: 'Date de cr',
        Type: 'Date',
        md: 4,
        Position: 21,
        GridField: false,
      },

      {
        Name: 'disease',
        Label: 'Disease',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'new_or_old',
        Position: 22,
        GridField: false,
      },
      {
        Name: 'icd10',
        Label: 'Main diagnosis ICD10',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'cim101', //change
        Position: 23,
        GridField: false,
      },
      {
        Name: 'id',
        Label: "Identifiant d'utilisateur",
        Type: 'Text',
        md: 4,
        Position: 24,
        GridField: false,
      },
      {
        Name: 'id_data',
        Label: 'Identifiant de la fiche',
        Type: 'Text',
        md: 4,
        Position: 25,
        GridField: false,
      },
      {
        Name: 'id_group',
        Label: 'Groupe',
        Type: 'Text',
        md: 4,
        Position: 26,
        GridField: false,
      },
      {
        Name: 'inr',
        Label: 'INR',
        Type: 'Number',
        md: 4,
        Position: 27,
        GridField: false,
      },
      {
        Name: 'major_findings',
        Label: 'Major findings',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'rfactor',
        Position: 28,
        GridField: false,
      },
      {
        Name: 'other_chief_complaint',
        Label: 'Other chief complaint',
        Type: 'Text',
        md: 4,
        Position: 29,
        GridField: false,
      },
      {
        Name: 'other_major_finding',
        Label: 'Other major finding',
        Type: 'Text',
        md: 4,
        Position: 30,
        GridField: false,
      },
      {
        Name: 'paralysis',
        Label: 'Paralysis',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn',
        Position: 31,
        GridField: false,
      },
      {
        Name: 'pe_vs_heart',
        Label: 'Heart rate',
        Type: 'Text',
        md: 4,
        Position: 32,
        GridField: false,
      },
      {
        Name: 'rec_status',
        Label: 'Status',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'rec_status',
        Position: 33,
        GridField: false,
      },
      {
        Name: 'referred_by_13a',
        Label: 'Referred by 13A form',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'yorn',
        Position: 34,
        GridField: false,
      },
      {
        Name: 's_bp',
        Label: 'Systolic pressure',
        Type: 'Number',
        md: 4,
        Position: 35,
        GridField: false,
      },
      {
        Name: 's_operation_author',
        Label: 'Operation performed by',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'doctor',
        Position: 36,
        GridField: false,
      },
      {
        Name: 's_operation_complication',
        Label: 'Complication',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'complication',
        Position: 37,
        GridField: false,
      },
      {
        Name: 's_operation_condition',
        Label: 'Condition of the operation',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'condition',
        Position: 38,
        GridField: false,
      },
      {
        Name: 's_operation_duration',
        Label: 'Duration of the operation (minutes)',
        Type: 'Text',
        md: 4,
        Position: 39,
        GridField: false,
      },
      {
        Name: 's_operation_finding',
        Label: 'Operation finding',
        Type: 'Text',
        md: 4,
        Position: 40,
        GridField: false,
      },
      {
        Name: 's_operation_name',
        Label: 'Name of the operation',
        Type: 'CheckBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        LookUpConfig: {
          Model: ModelLookUp,
          ParentValueField: 'id_data',
          ChildValueField: 'value',
          IdField: 'id_lookup',
          Field: 'id_question',
        },
        Multiple: true,
        md: 4,
        OptionType: 'cardio_surgery_op',
        Position: 41,
        GridField: false,
      },
      {
        Name: 'surgery_test',
        Label: 'Test',
        Type: 'Text',
        md: 4,
        Position: 42,
        GridField: false,
      },
      {
        Name: 'type_exam1',
        Label: 'At outpatients due to',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'type_exam1',
        GridField: false,
      },
      {
        Name: 'type_exam2',
        Label: 'Type of examination',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        md: 4,
        OptionType: 'type_exam2',
        Position: 44,
        GridField: false,
      },
      {
        Name: 'user_mod',
        Label: 'Auteur de la derni',
        Type: 'Text',
        md: 4,
        Position: 45,
        GridField: false,
      },
      {
        Name: 'weight',
        Label: 'Weight',
        Type: 'Number',
        md: 4,
        Position: 46,
        GridField: false,
      },
      {
        Name: 'main_diagnosis',
        Label: 'Main diagnosis',
        Type: 'SingleSelectLoad',
        Config: {
          ObjectName: 'vwICD10',
          IdField: 'value',
          TextField: 'label',
          MinTextLength: 1,
        },
        md: 4,
        Editfield: false,
        Position: 47,
      },
      {
        Name: 'main_diagnosis_notes',
        Label: 'Comment to main diagnosis',
        Type: 'Text',
        md: 4,
        Position: 48,
        GridField: false,
      },

      // -----------------------------------------------------------------
      // Form АМ-1Б (А/611, appendix 11) — tender item 4.1.
      // Labels are the register's own column headings, so they are Mongolian
      // here rather than English like the older descriptors above.
      // -----------------------------------------------------------------
      {
        Name: 'exam_type_icd',
        Label: 'Үзлэгийн төрөл /Z00-Z40/',
        Type: 'Text',
        md: 4,
        Position: 49,
        GridField: false,
      },
      {
        Name: 'cause_icd10',
        Label: 'Өвчний шалтгаан /ӨОУА-10/',
        Type: 'Text',
        md: 4,
        Position: 50,
        GridField: false,
      },
      {
        Name: 'procedure_icd9',
        Label: 'Хийгдсэн ажилбар /ҮОУА-9/',
        Type: 'Text',
        md: 4,
        Position: 51,
        GridField: false,
      },
      {
        // `yorn` is labelled Yes/No in English. It is used because it is what
        // referred_by_13a and paralysis already use on this form, so the three
        // read consistently; a Mongolian option list for all of them is on the
        // list for ЗСҮТ rather than something to invent here.
        Name: 'has_complication',
        Label: 'Хүндрэлтэй эсэх',
        Type: 'RadioBox',
        Config: { IdField: 'Value', TextField: 'Label' },
        OptionType: 'yorn',
        md: 4,
        Position: 52,
        GridField: false,
      },
      {
        Name: 'incapacity_days',
        Label: 'Хөдөлмөрийн чадвар түр алдалтын хоног',
        Type: 'Number',
        md: 4,
        Position: 53,
        GridField: false,
      },
    ],
  ];

  this.ObjectName = 'Visit';
  this.Model = Model;
  this.OptionTypes = Models.OptionTypes;
  this.PK = 'id_data';
  this.NewObject = {};
  this.TitleObject = {
    Title: 'Visit',
    NewObjectTitle: 'Visit create',
    EditObjectTitle: 'Visit edit',
  };
}

module.exports = VisitConfig;
